const collegeData = [
  {
    "state": "Jammu Kashmir",
    "course": "MBBS",
    "name": "Sher-I-Kashmir Instt. of Medical Sciences",
    "city": "Srinagar",
    "est": "1988",
    "seats": "125",
    "type": "State Govt.",
    "filterType": "Govt",
    "link": "jammu-kashmir-mbbs-counselling.html"
  },
  {
    "state": "Jammu Kashmir",
    "course": "MBBS",
    "name": "All India Institute of Medical Sciences",
    "city": "Vijaypur, Jammu",
    "est": "2021",
    "seats": "100",
    "type": "Central Govt.",
    "filterType": "Govt",
    "link": "jammu-kashmir-mbbs-counselling.html"
  },
  {
    "state": "Jammu Kashmir",
    "course": "MBBS",
    "name": "Shri Mata Vaishno Devi Institute of Medical Excellence",
    "city": "Katra",
    "est": "2025",
    "seats": "50",
    "type": "Private",
    "filterType": "Private",
    "link": "jammu-kashmir-mbbs-counselling.html"
  },
  {
    "state": "Goa",
    "course": "AYUSH",
    "name": "All India Institute Of Ayurveda (North Goa)",
    "city": "Dhargal, Pernem",
    "est": "Govt.",
    "seats": "2022",
    "type": "100",
    "filterType": "Private",
    "link": "goa-ayush-counselling.html"
  },
  {
    "state": "Goa",
    "course": "AYUSH",
    "name": "Gomantak Ayurveda Mahavidyalaya & Research Centre",
    "city": "Vajem, Shiroda",
    "est": "Private",
    "seats": "1992",
    "type": "60",
    "filterType": "Private",
    "link": "goa-ayush-counselling.html"
  },
  {
    "state": "Karnataka",
    "course": "MBBS",
    "name": "Karnataka Institute of Medical Sciences",
    "city": "Hubballi",
    "est": "1957",
    "seats": "200",
    "type": "State Govt.",
    "filterType": "Govt",
    "link": "karnataka-mbbs-counselling.html"
  },
  {
    "state": "Karnataka",
    "course": "MBBS",
    "name": "Vijaynagar Institute of Medical Sciences",
    "city": "Bellary",
    "est": "1961",
    "seats": "250",
    "type": "State Govt.",
    "filterType": "Govt",
    "link": "karnataka-mbbs-counselling.html"
  },
  {
    "state": "Karnataka",
    "course": "MBBS",
    "name": "Belagavi Institute of Medical Sciences",
    "city": "Belagavi",
    "est": "2006",
    "seats": "200",
    "type": "State Govt.",
    "filterType": "Govt",
    "link": "karnataka-mbbs-counselling.html"
  },
  {
    "state": "Karnataka",
    "course": "MBBS",
    "name": "Hasan Institute of Medical Sciences",
    "city": "Hasan",
    "est": "2006",
    "seats": "200",
    "type": "State Govt.",
    "filterType": "Govt",
    "link": "karnataka-mbbs-counselling.html"
  },
  {
    "state": "Karnataka",
    "course": "MBBS",
    "name": "Mandya Institute of Medical Sciences",
    "city": "Mandya",
    "est": "2006",
    "seats": "150",
    "type": "State Govt.",
    "filterType": "Govt",
    "link": "karnataka-mbbs-counselling.html"
  },
  {
    "state": "Karnataka",
    "course": "MBBS",
    "name": "Bidar Institute of Medical Sciences",
    "city": "Bidar",
    "est": "2007",
    "seats": "200",
    "type": "State Govt.",
    "filterType": "Govt",
    "link": "karnataka-mbbs-counselling.html"
  },
  {
    "state": "Karnataka",
    "course": "MBBS",
    "name": "Raichur Institute of Medical Sciences",
    "city": "Raichur",
    "est": "2007",
    "seats": "200",
    "type": "State Govt.",
    "filterType": "Govt",
    "link": "karnataka-mbbs-counselling.html"
  },
  {
    "state": "Karnataka",
    "course": "MBBS",
    "name": "Shimoga Institute of Medical Sciences",
    "city": "Shimoga",
    "est": "2007",
    "seats": "150",
    "type": "State Govt.",
    "filterType": "Govt",
    "link": "karnataka-mbbs-counselling.html"
  },
  {
    "state": "Karnataka",
    "course": "MBBS",
    "name": "Gadag Institute of Medical Sciences",
    "city": "Gadag",
    "est": "2015",
    "seats": "150",
    "type": "State Govt.",
    "filterType": "Govt",
    "link": "karnataka-mbbs-counselling.html"
  },
  {
    "state": "Karnataka",
    "course": "MBBS",
    "name": "Gulbarga Institute of Medical Sciences",
    "city": "Gulbarga",
    "est": "2015",
    "seats": "200",
    "type": "State Govt.",
    "filterType": "Govt",
    "link": "karnataka-mbbs-counselling.html"
  },
  {
    "state": "Karnataka",
    "course": "MBBS",
    "name": "Koppal Institute of Medical Sciences",
    "city": "Koppal",
    "est": "2015",
    "seats": "150",
    "type": "State Govt.",
    "filterType": "Govt",
    "link": "karnataka-mbbs-counselling.html"
  },
  {
    "state": "Karnataka",
    "course": "MBBS",
    "name": "Chamarajanagar Institute of Medical sciences",
    "city": "Chamarajanagar",
    "est": "2016",
    "seats": "150",
    "type": "State Govt.",
    "filterType": "Govt",
    "link": "karnataka-mbbs-counselling.html"
  },
  {
    "state": "Karnataka",
    "course": "MBBS",
    "name": "Karwar Institute of Medical Sciences",
    "city": "Karwar",
    "est": "2016",
    "seats": "150",
    "type": "State Govt.",
    "filterType": "Govt",
    "link": "karnataka-mbbs-counselling.html"
  },
  {
    "state": "Karnataka",
    "course": "MBBS",
    "name": "Kodagu Institute of Medical Sciences",
    "city": "Kodagu",
    "est": "2016",
    "seats": "150",
    "type": "State Govt.",
    "filterType": "Govt",
    "link": "karnataka-mbbs-counselling.html"
  },
  {
    "state": "Karnataka",
    "course": "MBBS",
    "name": "Chikkballapura Institute Of Medical Sciences",
    "city": "Chikkballapura",
    "est": "2021",
    "seats": "150",
    "type": "State Govt.",
    "filterType": "Govt",
    "link": "karnataka-mbbs-counselling.html"
  },
  {
    "state": "Karnataka",
    "course": "MBBS",
    "name": "Chikkamagaluru Institute Of Medical Science",
    "city": "Chikkamagluru",
    "est": "2022",
    "seats": "150",
    "type": "State Govt.",
    "filterType": "Govt",
    "link": "karnataka-mbbs-counselling.html"
  },
  {
    "state": "Karnataka",
    "course": "MBBS",
    "name": "Haveri Institute Of Medica; Science",
    "city": "Haveri",
    "est": "2022",
    "seats": "150",
    "type": "State Govt.",
    "filterType": "Govt",
    "link": "karnataka-mbbs-counselling.html"
  },
  {
    "state": "Karnataka",
    "course": "MBBS",
    "name": "Yadgiri Institute Of Medical Sciences",
    "city": "Yadgiri",
    "est": "2022",
    "seats": "150",
    "type": "State Govt.",
    "filterType": "Govt",
    "link": "karnataka-mbbs-counselling.html"
  },
  {
    "state": "Karnataka",
    "course": "MBBS",
    "name": "Adichunchanagiri Institute of Medical Sciences",
    "city": "Bellur",
    "est": "1985",
    "seats": "250",
    "type": "Trust",
    "filterType": "Private",
    "link": "karnataka-mbbs-counselling.html"
  },
  {
    "state": "Karnataka",
    "course": "MBBS",
    "name": "Khaja Bandanawaz University - FMS (Muslim Minority)",
    "city": "Gulbarga",
    "est": "2000",
    "seats": "150",
    "type": "Trust",
    "filterType": "Private",
    "link": "karnataka-mbbs-counselling.html"
  },
  {
    "state": "Karnataka",
    "course": "MBBS",
    "name": "A J Institute of Medical Sciences & Research Centre (Tulu Min.)",
    "city": "Mangalore",
    "est": "2002",
    "seats": "250",
    "type": "Trust",
    "filterType": "Private",
    "link": "karnataka-mbbs-counselling.html"
  },
  {
    "state": "Karnataka",
    "course": "MBBS",
    "name": "Vydehi Institute Of Medical Sciences & Research Centre",
    "city": "Bangalore",
    "est": "2002",
    "seats": "250",
    "type": "Trust",
    "filterType": "Private",
    "link": "karnataka-mbbs-counselling.html"
  },
  {
    "state": "Karnataka",
    "course": "MBBS",
    "name": "S S Institute of Medical Sciences & Research Centre",
    "city": "Davangere",
    "est": "2006",
    "seats": "200",
    "type": "Trust",
    "filterType": "Private",
    "link": "karnataka-mbbs-counselling.html"
  },
  {
    "state": "Karnataka",
    "course": "MBBS",
    "name": "Sapthagiri Institute of Medical Sciences (Kodava Min.)",
    "city": "Bangalore",
    "est": "2011",
    "seats": "250",
    "type": "Trust",
    "filterType": "Private",
    "link": "karnataka-mbbs-counselling.html"
  },
  {
    "state": "Karnataka",
    "course": "MBBS",
    "name": "Srinivas Institute of Medical Research Centre (Tulu Min.)",
    "city": "Mangalore",
    "est": "2011",
    "seats": "250",
    "type": "Trust",
    "filterType": "Private",
    "link": "karnataka-mbbs-counselling.html"
  },
  {
    "state": "Karnataka",
    "course": "MBBS",
    "name": "Subbaiah Institute of Medical Sciences (Telugu Min.)",
    "city": "Shimoga",
    "est": "2012",
    "seats": "250",
    "type": "Trust",
    "filterType": "Private",
    "link": "karnataka-mbbs-counselling.html"
  },
  {
    "state": "Karnataka",
    "course": "MBBS",
    "name": "BGS Global Institute of Medical Sciences",
    "city": "Bangalore",
    "est": "2013",
    "seats": "150",
    "type": "Trust",
    "filterType": "Private",
    "link": "karnataka-mbbs-counselling.html"
  },
  {
    "state": "Karnataka",
    "course": "MBBS",
    "name": "Shridevi Institute of Medical Sciences & Research Hospital",
    "city": "Tumkur",
    "est": "2013",
    "seats": "250",
    "type": "Trust",
    "filterType": "Private",
    "link": "karnataka-mbbs-counselling.html"
  },
  {
    "state": "Karnataka",
    "course": "MBBS",
    "name": "Akash Institute of Medical Sciences (Telugu Min.)",
    "city": "Bangalore",
    "est": "2016",
    "seats": "250",
    "type": "Trust",
    "filterType": "Private",
    "link": "karnataka-mbbs-counselling.html"
  },
  {
    "state": "Karnataka",
    "course": "MBBS",
    "name": "Kanachur Institute of Medical Sciences (Muslim Min.)",
    "city": "Mangalore",
    "est": "2016",
    "seats": "200",
    "type": "Trust",
    "filterType": "Private",
    "link": "karnataka-mbbs-counselling.html"
  },
  {
    "state": "Karnataka",
    "course": "MBBS",
    "name": "Sri Siddhartha Institute of Medical Sciences",
    "city": "Bangalore",
    "est": "2019",
    "seats": "150",
    "type": "Trust",
    "filterType": "Private",
    "link": "karnataka-mbbs-counselling.html"
  },
  {
    "state": "Karnataka",
    "course": "MBBS",
    "name": "Dr. Chandramma Dayananda Sagar Instt.",
    "city": "Harohalli",
    "est": "2020",
    "seats": "200",
    "type": "Trust",
    "filterType": "Private",
    "link": "karnataka-mbbs-counselling.html"
  },
  {
    "state": "Karnataka",
    "course": "MBBS",
    "name": "Sri Madhusudan Sai Institute of Medical Sciences",
    "city": "Chikballapur",
    "est": "2023",
    "seats": "50",
    "type": "Trust",
    "filterType": "Private",
    "link": "karnataka-mbbs-counselling.html"
  },
  {
    "state": "Karnataka",
    "course": "MBBS",
    "name": "PES University Institute of Medical Sciences & Research",
    "city": "Bangalore",
    "est": "2024",
    "seats": "150",
    "type": "Trust",
    "filterType": "Private",
    "link": "karnataka-mbbs-counselling.html"
  },
  {
    "state": "Karnataka",
    "course": "MBBS",
    "name": "S R Patil Medical Sciences & Research Centre",
    "city": "Bagalkot",
    "est": "2024",
    "seats": "100",
    "type": "Trust",
    "filterType": "Private",
    "link": "karnataka-mbbs-counselling.html"
  },
  {
    "state": "Karnataka",
    "course": "MBBS",
    "name": "Farookh Academy of Medical Education Hosp",
    "city": "Mysuru",
    "est": "2025",
    "seats": "100",
    "type": "Trust",
    "filterType": "Private",
    "link": "karnataka-mbbs-counselling.html"
  },
  {
    "state": "Karnataka",
    "course": "MBBS",
    "name": "K.S.Hegde Medical Academy",
    "city": "Mangalore",
    "est": "1999",
    "seats": "250",
    "type": "Deemed",
    "filterType": "Deemed",
    "link": "karnataka-mbbs-counselling.html"
  },
  {
    "state": "Karnataka",
    "course": "MBBS",
    "name": "Jagadguru Gangadhar Mahaswamigalu Moorusavirmath MC",
    "city": "Hubballi",
    "est": "2021",
    "seats": "200",
    "type": "Deemed",
    "filterType": "Deemed",
    "link": "karnataka-mbbs-counselling.html"
  },
  {
    "state": "Up",
    "course": "MBBS",
    "name": "King George's Medical University (KGMU) (State Govt.)",
    "city": "Lucknow",
    "est": "1911",
    "seats": "250",
    "type": "\u20b954,600",
    "filterType": "Private",
    "link": "up-mbbs-counselling.html"
  },
  {
    "state": "Up",
    "course": "MBBS",
    "name": "Institute of Medical Sciences, BHU (Central Govt.)",
    "city": "Varanasi",
    "est": "1960",
    "seats": "100",
    "type": "Central Norms",
    "filterType": "Govt",
    "link": "up-mbbs-counselling.html"
  },
  {
    "state": "Up",
    "course": "MBBS",
    "name": "UP University of Medical Sciences (UPUMS) (State Govt.)",
    "city": "Etawah",
    "est": "2006",
    "seats": "200",
    "type": "\u20b940,000",
    "filterType": "Private",
    "link": "up-mbbs-counselling.html"
  },
  {
    "state": "Up",
    "course": "MBBS",
    "name": "Dr. RML Institute of Medical Sciences (State Govt.)",
    "city": "Lucknow",
    "est": "2017",
    "seats": "200",
    "type": "\u20b940,000",
    "filterType": "Private",
    "link": "up-mbbs-counselling.html"
  },
  {
    "state": "Up",
    "course": "MBBS",
    "name": "All India Institute of Medical Sciences (AIIMS)",
    "city": "Gorakhpur",
    "est": "2019",
    "seats": "125",
    "type": "AIIMS Norms",
    "filterType": "Govt",
    "link": "up-mbbs-counselling.html"
  },
  {
    "state": "Up",
    "course": "MBBS",
    "name": "All India Institute of Medical Sciences (AIIMS)",
    "city": "Rae Bareli",
    "est": "2019",
    "seats": "100",
    "type": "AIIMS Norms",
    "filterType": "Govt",
    "link": "up-mbbs-counselling.html"
  },
  {
    "state": "Up",
    "course": "MBBS",
    "name": "Government Institute of Medical Sciences (GIMS) (State Govt.)",
    "city": "Greater Noida",
    "est": "2019",
    "seats": "100",
    "type": "\u20b968,500",
    "filterType": "Private",
    "link": "up-mbbs-counselling.html"
  },
  {
    "state": "Up",
    "course": "MBBS",
    "name": "Maharshi Devraha Baba ASMC (State Govt.)",
    "city": "Deoria",
    "est": "2021",
    "seats": "100",
    "type": "~\u20b936,000",
    "filterType": "Private",
    "link": "up-mbbs-counselling.html"
  },
  {
    "state": "Up",
    "course": "MBBS",
    "name": "Uma Nath Singh ASMC Society (State Govt.)",
    "city": "Jaunpur",
    "est": "2021",
    "seats": "100",
    "type": "\u20b936,000",
    "filterType": "Private",
    "link": "up-mbbs-counselling.html"
  },
  {
    "state": "Up",
    "course": "MBBS",
    "name": "Baba Kina Ram ASMC & Hospital (State Govt.)",
    "city": "Chandauli",
    "est": "2024",
    "seats": "100",
    "type": "~\u20b936,000",
    "filterType": "Private",
    "link": "up-mbbs-counselling.html"
  },
  {
    "state": "Up",
    "course": "MBBS",
    "name": "Shri Ram Murti Smarak Institute of Medical Sciences",
    "city": "Bareilly",
    "est": "2005",
    "seats": "150",
    "type": "\u20b913,73,760",
    "filterType": "Private",
    "link": "up-mbbs-counselling.html"
  },
  {
    "state": "Up",
    "course": "MBBS",
    "name": "Sarswati Institute of Medical Sciences",
    "city": "Hapur",
    "est": "2008",
    "seats": "250",
    "type": "\u20b911,81,671",
    "filterType": "Private",
    "link": "up-mbbs-counselling.html"
  },
  {
    "state": "Up",
    "course": "MBBS",
    "name": "Hind Institute of Medical Sciences",
    "city": "Barabanki",
    "est": "2009",
    "seats": "100",
    "type": "\u20b911,70,612",
    "filterType": "Private",
    "link": "up-mbbs-counselling.html"
  },
  {
    "state": "Up",
    "course": "MBBS",
    "name": "School of Medical Sciences & Research (Sharda University)",
    "city": "Greater Noida",
    "est": "2009",
    "seats": "250",
    "type": "\u20b912,69,319",
    "filterType": "Private",
    "link": "up-mbbs-counselling.html"
  },
  {
    "state": "Up",
    "course": "MBBS",
    "name": "Career Institute of Medical Sciences (Muslim Minority)",
    "city": "Lucknow",
    "est": "2011",
    "seats": "150",
    "type": "\u20b915,80,000",
    "filterType": "Private",
    "link": "up-mbbs-counselling.html"
  },
  {
    "state": "Up",
    "course": "MBBS",
    "name": "Mayo Institute of Medical Sciences",
    "city": "Barabanki",
    "est": "2012",
    "seats": "250",
    "type": "\u20b911,21,162",
    "filterType": "Private",
    "link": "up-mbbs-counselling.html"
  },
  {
    "state": "Up",
    "course": "MBBS",
    "name": "Integral Institute of Medical Sciences (Muslim Minority)",
    "city": "Lucknow",
    "est": "2013",
    "seats": "150",
    "type": "\u20b917,00,000",
    "filterType": "Private",
    "link": "up-mbbs-counselling.html"
  },
  {
    "state": "Up",
    "course": "MBBS",
    "name": "Rajshree Medical Research Institute",
    "city": "Bareilly",
    "est": "2014",
    "seats": "250",
    "type": "\u20b912,28,406",
    "filterType": "Private",
    "link": "up-mbbs-counselling.html"
  },
  {
    "state": "Up",
    "course": "MBBS",
    "name": "Heritage Institute of Medical Sciences",
    "city": "Varanasi",
    "est": "2015",
    "seats": "200",
    "type": "\u20b913,21,492",
    "filterType": "Private",
    "link": "up-mbbs-counselling.html"
  },
  {
    "state": "Up",
    "course": "MBBS",
    "name": "Hind Institute of Medical Sciences",
    "city": "Sitapur",
    "est": "2015",
    "seats": "150",
    "type": "\u20b910,77,229",
    "filterType": "Private",
    "link": "up-mbbs-counselling.html"
  },
  {
    "state": "Up",
    "course": "MBBS",
    "name": "Prasad Institute of Medical Sciences",
    "city": "Lucknow",
    "est": "2016",
    "seats": "150",
    "type": "\u20b911,03,932",
    "filterType": "Private",
    "link": "up-mbbs-counselling.html"
  },
  {
    "state": "Up",
    "course": "MBBS",
    "name": "Venkateshwara Institute of Medical Sciences",
    "city": "Amroha",
    "est": "2016",
    "seats": "250",
    "type": "\u20b911,10,508",
    "filterType": "Private",
    "link": "up-mbbs-counselling.html"
  },
  {
    "state": "Up",
    "course": "MBBS",
    "name": "National Capital Region Institute of Medical Sciences",
    "city": "Meerut",
    "est": "2018",
    "seats": "150",
    "type": "\u20b912,19,917",
    "filterType": "Private",
    "link": "up-mbbs-counselling.html"
  },
  {
    "state": "Up",
    "course": "MBBS",
    "name": "Noida International Institute Of Medical Sciences",
    "city": "Greater Noida",
    "est": "2020",
    "seats": "150",
    "type": "\u20b911,92,211",
    "filterType": "Private",
    "link": "up-mbbs-counselling.html"
  },
  {
    "state": "Up",
    "course": "MBBS",
    "name": "United Institute of Medical Sciences",
    "city": "Prayagraj",
    "est": "2020",
    "seats": "150",
    "type": "\u20b911,90,401",
    "filterType": "Private",
    "link": "up-mbbs-counselling.html"
  },
  {
    "state": "Up",
    "course": "MBBS",
    "name": "Ajay Sangaal Institute of Medical Sciences",
    "city": "Shamli",
    "est": "2024",
    "seats": "150",
    "type": "~\u20b911,00,000",
    "filterType": "Private",
    "link": "up-mbbs-counselling.html"
  },
  {
    "state": "Up",
    "course": "MBBS",
    "name": "Dr. B.S. Kushwah Institute of Medical Sciences",
    "city": "Kanpur",
    "est": "2024",
    "seats": "150",
    "type": "~\u20b911,00,000",
    "filterType": "Private",
    "link": "up-mbbs-counselling.html"
  },
  {
    "state": "Bihar",
    "course": "MBBS",
    "name": "\u20b99,35,000",
    "city": "\u20b92,50,000",
    "est": "Dev: \u20b91.2L + Amenity: \u20b950k",
    "seats": "\u20b91,00,000",
    "type": "",
    "filterType": "Private",
    "link": "bihar-mbbs-counselling.html"
  },
  {
    "state": "Bihar",
    "course": "MBBS",
    "name": "\u20b99,63,000",
    "city": "\u20b93,00,000",
    "est": "Adm: \u20b950k + Amenity: \u20b92L",
    "seats": "\u20b950,000",
    "type": "",
    "filterType": "Private",
    "link": "bihar-mbbs-counselling.html"
  },
  {
    "state": "Bihar",
    "course": "MBBS",
    "name": "\u20b910,38,000",
    "city": "\u20b93,00,000",
    "est": "Adm: \u20b950k + Amenity: \u20b91.3L",
    "seats": "\u20b92,00,000",
    "type": "",
    "filterType": "Private",
    "link": "bihar-mbbs-counselling.html"
  },
  {
    "state": "Bihar",
    "course": "MBBS",
    "name": "\u20b916,25,000",
    "city": "\u20b93,20,000",
    "est": "Transport: \u20b950k",
    "seats": "\u20b92,00,000",
    "type": "",
    "filterType": "Private",
    "link": "bihar-mbbs-counselling.html"
  },
  {
    "state": "Bihar",
    "course": "MBBS",
    "name": "\u20b913,50,000",
    "city": "\u20b93,00,000",
    "est": "Dev: \u20b950k",
    "seats": "\u20b91,00,000",
    "type": "",
    "filterType": "Private",
    "link": "bihar-mbbs-counselling.html"
  },
  {
    "state": "Bihar",
    "course": "MBBS",
    "name": "\u20b910,00,000",
    "city": "\u20b93,00,000",
    "est": "Dev: \u20b91L + Amenity: \u20b91L",
    "seats": "\u20b92,00,000",
    "type": "",
    "filterType": "Private",
    "link": "bihar-mbbs-counselling.html"
  },
  {
    "state": "Bihar",
    "course": "MBBS",
    "name": "\u20b913,00,000",
    "city": "\u20b93,00,000",
    "est": "-",
    "seats": "-",
    "type": "",
    "filterType": "Private",
    "link": "bihar-mbbs-counselling.html"
  },
  {
    "state": "Bihar",
    "course": "MBBS",
    "name": "\u20b912,00,000",
    "city": "\u20b93,00,000",
    "est": "-",
    "seats": "-",
    "type": "",
    "filterType": "Private",
    "link": "bihar-mbbs-counselling.html"
  },
  {
    "state": "Bihar",
    "course": "MBBS",
    "name": "\u20b915,75,000",
    "city": "\u20b93,20,000",
    "est": "Adm: \u20b950k",
    "seats": "\u20b91,00,000",
    "type": "",
    "filterType": "Private",
    "link": "bihar-mbbs-counselling.html"
  },
  {
    "state": "Bihar",
    "course": "MBBS",
    "name": "Indira Gandhi Institute of Medical Sciences",
    "city": "Patna",
    "est": "2011",
    "seats": "150",
    "type": "State Govt.",
    "filterType": "Govt",
    "link": "bihar-mbbs-counselling.html"
  },
  {
    "state": "Bihar",
    "course": "MBBS",
    "name": "All India Institute of Medical Sciences",
    "city": "Patna",
    "est": "2012",
    "seats": "125",
    "type": "Central Govt.",
    "filterType": "Govt",
    "link": "bihar-mbbs-counselling.html"
  },
  {
    "state": "Bihar",
    "course": "MBBS",
    "name": "Bhagwan Mahavir Institute of Medical Sciences (VIMS)",
    "city": "Pawapuri",
    "est": "2013",
    "seats": "120",
    "type": "State Govt.",
    "filterType": "Govt",
    "link": "bihar-mbbs-counselling.html"
  },
  {
    "state": "Bihar",
    "course": "MBBS",
    "name": "Radha Devi Jageshwari Memorial MCH",
    "city": "Muzaffarpur",
    "est": "2021",
    "seats": "200",
    "type": "Society",
    "filterType": "Private",
    "link": "bihar-mbbs-counselling.html"
  },
  {
    "state": "Bihar",
    "course": "MBBS",
    "name": "Shree Narayan Medical Institute and Hospital",
    "city": "Saharsa",
    "est": "2021",
    "seats": "150",
    "type": "Trust",
    "filterType": "Private",
    "link": "bihar-mbbs-counselling.html"
  },
  {
    "state": "Bihar",
    "course": "MBBS",
    "name": "Viraat Ramayan Institute of Medical Sciences",
    "city": "Motihari",
    "est": "2025",
    "seats": "50",
    "type": "Company",
    "filterType": "Private",
    "link": "bihar-mbbs-counselling.html"
  },
  {
    "state": "Odisha",
    "course": "MBBS",
    "name": "Veer Surendra Sai Institute of Medical Sciences and Research",
    "city": "Burla",
    "est": "1959",
    "seats": "200",
    "type": "State Govt.",
    "filterType": "Govt",
    "link": "odisha-mbbs-counselling.html"
  },
  {
    "state": "Odisha",
    "course": "MBBS",
    "name": "All India Institute of Medical Sciences",
    "city": "Bhubaneswar",
    "est": "2012",
    "seats": "125",
    "type": "Central Govt.",
    "filterType": "Govt",
    "link": "odisha-mbbs-counselling.html"
  },
  {
    "state": "Odisha",
    "course": "MBBS",
    "name": "DRIEMS Institute of Health Sciences and Hospital",
    "city": "Kairapari",
    "est": "2023",
    "seats": "100",
    "type": "Society",
    "filterType": "Private",
    "link": "odisha-mbbs-counselling.html"
  },
  {
    "state": "Odisha",
    "course": "MBBS",
    "name": "Institute of Medical Sciences & SUM Hospital",
    "city": "Bhubaneswar",
    "est": "2007",
    "seats": "250",
    "type": "Deemed",
    "filterType": "Deemed",
    "link": "odisha-mbbs-counselling.html"
  },
  {
    "state": "Odisha",
    "course": "MBBS",
    "name": "Kalinga Institute of Medical Sciences",
    "city": "Bhubaneswar",
    "est": "2007",
    "seats": "250",
    "type": "Deemed",
    "filterType": "Deemed",
    "link": "odisha-mbbs-counselling.html"
  },
  {
    "state": "Odisha",
    "course": "MBBS",
    "name": "Institute of Medical Sciences and SUM Hospital Campus II",
    "city": "Bhubaneswar",
    "est": "2024",
    "seats": "250",
    "type": "Deemed",
    "filterType": "Deemed",
    "link": "odisha-mbbs-counselling.html"
  },
  {
    "state": "Uttarakhand",
    "course": "MBBS",
    "name": "Veer Chandra Singh Garhwali Govt. Medical Sc. & Research Instt, Srinagar",
    "city": "Uttrakhand Technical University",
    "est": "2008",
    "seats": "150",
    "type": "State Govt.",
    "filterType": "Govt",
    "link": "uttarakhand-mbbs-counselling.html"
  },
  {
    "state": "Uttarakhand",
    "course": "MBBS",
    "name": "All India Institute of Medical Sciences, Rishikesh",
    "city": "AIIMS (New Delhi)",
    "est": "2021",
    "seats": "125",
    "type": "Central Govt.",
    "filterType": "Govt",
    "link": "uttarakhand-mbbs-counselling.html"
  },
  {
    "state": "Uttarakhand",
    "course": "MBBS",
    "name": "Soban Singh Jeena Government Institute of Medical Science & Research, Almora",
    "city": "HNBUMU, Dehradun",
    "est": "2021",
    "seats": "100",
    "type": "State Govt.",
    "filterType": "Govt",
    "link": "uttarakhand-mbbs-counselling.html"
  },
  {
    "state": "Uttarakhand",
    "course": "MBBS",
    "name": "Government Medical college and Hospital , Haridwar",
    "city": "HNBUMU, Dehradun",
    "est": "2024",
    "seats": "100",
    "type": "State Govt.",
    "filterType": "Govt",
    "link": "uttarakhand-mbbs-counselling.html"
  },
  {
    "state": "Uttarakhand",
    "course": "MBBS",
    "name": "Himalayan Institute of Medical Sciences, Dehradun",
    "city": "Swami Rama Himalayan University",
    "est": "1995",
    "seats": "150",
    "type": "Trust",
    "filterType": "Private",
    "link": "uttarakhand-mbbs-counselling.html"
  },
  {
    "state": "Uttarakhand",
    "course": "MBBS",
    "name": "Shri Guru Ram Rai Institute of Medical & Health Sciences, Dehradun",
    "city": "Shri Guru Ram Rai University",
    "est": "2006",
    "seats": "250",
    "type": "Society",
    "filterType": "Private",
    "link": "uttarakhand-mbbs-counselling.html"
  },
  {
    "state": "Uttarakhand",
    "course": "MBBS",
    "name": "Gautam Buddha Chikitsa Mahavidyalaya, Dehradun",
    "city": "Ras Bihari Bose Subharti University",
    "est": "2022",
    "seats": "150",
    "type": "Trust",
    "filterType": "Private",
    "link": "uttarakhand-mbbs-counselling.html"
  },
  {
    "state": "Uttarakhand",
    "course": "MBBS",
    "name": "Graphic Era Institute of Medical Sciences, Dehradun",
    "city": "Graphic Era Institute of Medical Sciences",
    "est": "2024",
    "seats": "150",
    "type": "Deemed Univ.",
    "filterType": "Deemed",
    "link": "uttarakhand-mbbs-counselling.html"
  },
  {
    "state": "Jammu Kashmir",
    "course": "AYUSH",
    "name": "Jammu Institute of Ayurved & ResearchJammu",
    "city": "Private",
    "est": "1999",
    "seats": "60",
    "type": "",
    "filterType": "Private",
    "link": "jammu-kashmir-ayush-counselling.html"
  },
  {
    "state": "Uttarakhand",
    "course": "AYUSH",
    "name": "Rishikul Campus, Haridwar (U.A.U.)",
    "city": "75",
    "est": "64",
    "seats": "11",
    "type": "\u20b91,50,000",
    "filterType": "Private",
    "link": "uttarakhand-ayush-counselling.html"
  },
  {
    "state": "Uttarakhand",
    "course": "AYUSH",
    "name": "Gurukul Campus, Haridwar (U.A.U.)",
    "city": "75",
    "est": "64",
    "seats": "11",
    "type": "\u20b91,78,400",
    "filterType": "Private",
    "link": "uttarakhand-ayush-counselling.html"
  },
  {
    "state": "Uttarakhand",
    "course": "AYUSH",
    "name": "Faculty of Ayurveda, Main Campus, U.A.U. Harrawala, Dehradun",
    "city": "75",
    "est": "64",
    "seats": "11",
    "type": "\u20b91,50,000",
    "filterType": "Private",
    "link": "uttarakhand-ayush-counselling.html"
  },
  {
    "state": "Uttarakhand",
    "course": "AYUSH",
    "name": "Patanjali Ayurvigyan & Research Institute",
    "city": "Haridwar",
    "est": "100",
    "seats": "50",
    "type": "50",
    "filterType": "Private",
    "link": "uttarakhand-ayush-counselling.html"
  },
  {
    "state": "Uttarakhand",
    "course": "AYUSH",
    "name": "Qudra Institute of Ayurveda",
    "city": "Roorkee, Haridwar",
    "est": "60",
    "seats": "30",
    "type": "30",
    "filterType": "Private",
    "link": "uttarakhand-ayush-counselling.html"
  },
  {
    "state": "Uttarakhand",
    "course": "AYUSH",
    "name": "Shivalik Institute Of Ayurveda & Research",
    "city": "Dehradun",
    "est": "60",
    "seats": "30",
    "type": "30",
    "filterType": "Private",
    "link": "uttarakhand-ayush-counselling.html"
  },
  {
    "state": "Uttarakhand",
    "course": "AYUSH",
    "name": "Doon Institute of Ayurveda Faculty",
    "city": "Shahaspur, Dehradun",
    "est": "60",
    "seats": "30",
    "type": "30",
    "filterType": "Private",
    "link": "uttarakhand-ayush-counselling.html"
  },
  {
    "state": "Uttarakhand",
    "course": "AYUSH",
    "name": "Om Ayurvedic & Research Center",
    "city": "Roorkee",
    "est": "-",
    "seats": "-",
    "type": "-",
    "filterType": "Private",
    "link": "uttarakhand-ayush-counselling.html"
  },
  {
    "state": "Uttarakhand",
    "course": "AYUSH",
    "name": "Bishamber Sahai Group Of Institutes",
    "city": "Roorkee",
    "est": "-",
    "seats": "-",
    "type": "-",
    "filterType": "Private",
    "link": "uttarakhand-ayush-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "MBBS",
    "name": "Rajashree Chatrapati Shahu Maharaj GMC",
    "city": "Kolhapur",
    "est": "2001",
    "seats": "150",
    "type": "State Govt.",
    "filterType": "Govt",
    "link": "maharashtra-mbbs-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "MBBS",
    "name": "All India Institute of Medical Sciences",
    "city": "Nagpur",
    "est": "2018",
    "seats": "125",
    "type": "Central Govt.",
    "filterType": "Govt",
    "link": "maharashtra-mbbs-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "MBBS",
    "name": "Government Medical college and District Hospital",
    "city": "Ratnagiri",
    "est": "2023",
    "seats": "100",
    "type": "State Govt.",
    "filterType": "Govt",
    "link": "maharashtra-mbbs-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "MBBS",
    "name": "Government Medical college",
    "city": "Ambernath",
    "est": "2024",
    "seats": "100",
    "type": "State Govt.",
    "filterType": "Govt",
    "link": "maharashtra-mbbs-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "MBBS",
    "name": "Mahatma Gandhi Institute of Medical Sciences",
    "city": "Wardha",
    "est": "1969",
    "seats": "100",
    "type": "As per FRA",
    "filterType": "Private",
    "link": "maharashtra-mbbs-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "MBBS",
    "name": "Dr. Vasantrao Pawar Med. Col. Hosp. & RC",
    "city": "Nashik",
    "est": "1990",
    "seats": "120",
    "type": "\u20b97,38,000",
    "filterType": "Private",
    "link": "maharashtra-mbbs-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "MBBS",
    "name": "Maharashtra Institute of Medical Sciences & Research",
    "city": "Latur",
    "est": "1990",
    "seats": "150",
    "type": "\u20b97,20,000",
    "filterType": "Private",
    "link": "maharashtra-mbbs-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "MBBS",
    "name": "N. K. P. Salve Instt. of Medical Sciences",
    "city": "Nagpur",
    "est": "1990",
    "seats": "200",
    "type": "\u20b99,23,000",
    "filterType": "Private",
    "link": "maharashtra-mbbs-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "MBBS",
    "name": "Maharashtra Institute of Medical Education & Research",
    "city": "Pune",
    "est": "1994",
    "seats": "150",
    "type": "\u20b99,45,000",
    "filterType": "Private",
    "link": "maharashtra-mbbs-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "MBBS",
    "name": "Indian Institute of Medical Science & Research (Minority)",
    "city": "Jalna",
    "est": "2013",
    "seats": "100",
    "type": "\u20b97,00,000",
    "filterType": "Private",
    "link": "maharashtra-mbbs-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "MBBS",
    "name": "SMBT Institute of Medical Sciences & RC",
    "city": "Nashik",
    "est": "2014",
    "seats": "150",
    "type": "\u20b910,25,000",
    "filterType": "Private",
    "link": "maharashtra-mbbs-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "MBBS",
    "name": "Prakash Institute of Medical Sciences & Research",
    "city": "Sangli",
    "est": "2016",
    "seats": "150",
    "type": "\u20b910,30,000",
    "filterType": "Private",
    "link": "maharashtra-mbbs-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "MBBS",
    "name": "Vedantaa Institute of Medical Sciences",
    "city": "Palghar",
    "est": "2017",
    "seats": "150",
    "type": "As per FRA",
    "filterType": "Private",
    "link": "maharashtra-mbbs-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "MBBS",
    "name": "Dr. N Y Tasgaonkar Institute of Medical Science",
    "city": "Raigad",
    "est": "2021",
    "seats": "100",
    "type": "As per FRA",
    "filterType": "Private",
    "link": "maharashtra-mbbs-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "MBBS",
    "name": "Shri Ramchandra Institute of Medical Sciences",
    "city": "Aurangabad",
    "est": "2024",
    "seats": "50",
    "type": "As per FRA",
    "filterType": "Private",
    "link": "maharashtra-mbbs-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "MBBS",
    "name": "Krishna Institute of Medical Sciences",
    "city": "Karad",
    "est": "1984",
    "seats": "250",
    "type": "Deemed",
    "filterType": "Deemed",
    "link": "maharashtra-mbbs-counselling.html"
  },
  {
    "state": "Tamil Nadu",
    "course": "MBBS",
    "name": "AIIMS Madurai",
    "city": "Madurai",
    "est": "2021",
    "seats": "50",
    "type": "Central Govt.",
    "filterType": "Govt",
    "link": "tamil-nadu-mbbs-counselling.html"
  },
  {
    "state": "Tamil Nadu",
    "course": "MBBS",
    "name": "PSG Institute of Medical Sciences",
    "city": "Coimbatore",
    "est": "1985",
    "seats": "250",
    "type": "Trust",
    "filterType": "Private",
    "link": "tamil-nadu-mbbs-counselling.html"
  },
  {
    "state": "Tamil Nadu",
    "course": "MBBS",
    "name": "Sree Mookambika Institute of Medical Sciences (Malayalam Min.)",
    "city": "Kanyakumari",
    "est": "2006",
    "seats": "150",
    "type": "Trust",
    "filterType": "Private",
    "link": "tamil-nadu-mbbs-counselling.html"
  },
  {
    "state": "Tamil Nadu",
    "course": "MBBS",
    "name": "Melmaruvathur Adiparashakti Inst of Medical Sciences",
    "city": "Kancheepuram",
    "est": "2008",
    "seats": "150",
    "type": "Trust",
    "filterType": "Private",
    "link": "tamil-nadu-mbbs-counselling.html"
  },
  {
    "state": "Tamil Nadu",
    "course": "MBBS",
    "name": "Karpaga Vinayaga Institute of Medical Sciences",
    "city": "Madhuranthagam",
    "est": "2009",
    "seats": "150",
    "type": "Trust",
    "filterType": "Private",
    "link": "tamil-nadu-mbbs-counselling.html"
  },
  {
    "state": "Tamil Nadu",
    "course": "MBBS",
    "name": "Karpagam Faculty of Medical Sciences & Research (Telugu Min.)",
    "city": "Coimbatore",
    "est": "2012",
    "seats": "150",
    "type": "Trust",
    "filterType": "Private",
    "link": "tamil-nadu-mbbs-counselling.html"
  },
  {
    "state": "Tamil Nadu",
    "course": "MBBS",
    "name": "KMCH Institute of Health sciences & Research",
    "city": "Coimbatore",
    "est": "2019",
    "seats": "150",
    "type": "Trust",
    "filterType": "Private",
    "link": "tamil-nadu-mbbs-counselling.html"
  },
  {
    "state": "Tamil Nadu",
    "course": "MBBS",
    "name": "Dhanalakshmi Srinivasan Inst. of Medical Sciences (Private Univ)",
    "city": "Perambalu",
    "est": "2023",
    "seats": "150",
    "type": "Trust",
    "filterType": "Private",
    "link": "tamil-nadu-mbbs-counselling.html"
  },
  {
    "state": "Tamil Nadu",
    "course": "MBBS",
    "name": "Kanyakumari Medical Mission Research Centre",
    "city": "Kanyakumari",
    "est": "2024",
    "seats": "100",
    "type": "Trust",
    "filterType": "Private",
    "link": "tamil-nadu-mbbs-counselling.html"
  },
  {
    "state": "Tamil Nadu",
    "course": "MBBS",
    "name": "SRM Medical Hospital & Research Centre",
    "city": "Kancheepuram",
    "est": "2005",
    "seats": "250",
    "type": "Deemed",
    "filterType": "Deemed",
    "link": "tamil-nadu-mbbs-counselling.html"
  },
  {
    "state": "Tamil Nadu",
    "course": "MBBS",
    "name": "Chettinad Hospital & Research Institute",
    "city": "Kanchipuram",
    "est": "2006",
    "seats": "250",
    "type": "Deemed",
    "filterType": "Deemed",
    "link": "tamil-nadu-mbbs-counselling.html"
  },
  {
    "state": "Jharkhand",
    "course": "MBBS",
    "name": "Rajendra Institute of Medical Sciences",
    "city": "Ranchi",
    "est": "1960",
    "seats": "180",
    "type": "State Govt.",
    "filterType": "Govt",
    "link": "jharkhand-mbbs-counselling.html"
  },
  {
    "state": "Jharkhand",
    "course": "MBBS",
    "name": "Patliputra Medical Colllege, (Shahed Nirmal Mahto)",
    "city": "Dhanbad",
    "est": "1969",
    "seats": "100",
    "type": "State Govt.",
    "filterType": "Govt",
    "link": "jharkhand-mbbs-counselling.html"
  },
  {
    "state": "Jharkhand",
    "course": "MBBS",
    "name": "All India Institute of Medical Sciences",
    "city": "Deoghar",
    "est": "2019",
    "seats": "125",
    "type": "Central Govt.",
    "filterType": "Govt",
    "link": "jharkhand-mbbs-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "AYUSH",
    "name": "Smt. K.G. Mittal Ayurved Mahavidyalaya",
    "city": "Mumbai",
    "est": "50 (8)",
    "seats": "\u20b965,000",
    "type": "",
    "filterType": "Private",
    "link": "maharashtra-ayush-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "AYUSH",
    "name": "Ayurved Mahavidyalaya",
    "city": "Sion, Mumbai",
    "est": "75 (11)",
    "seats": "\u20b965,000",
    "type": "",
    "filterType": "Private",
    "link": "maharashtra-ayush-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "AYUSH",
    "name": "Tilak Ayurved Mahavidyalaya",
    "city": "Pune",
    "est": "125 (19)",
    "seats": "\u20b965,000",
    "type": "",
    "filterType": "Private",
    "link": "maharashtra-ayush-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "AYUSH",
    "name": "SCM Aryangla Vaidyak Mahavidyalaya",
    "city": "Satara",
    "est": "63 (9)",
    "seats": "\u20b965,000",
    "type": "",
    "filterType": "Private",
    "link": "maharashtra-ayush-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "AYUSH",
    "name": "Sheth Govindji Raoji Ayurved Mahavidyalaya",
    "city": "Solapur",
    "est": "60 (9)",
    "seats": "\u20b965,000",
    "type": "",
    "filterType": "Private",
    "link": "maharashtra-ayush-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "AYUSH",
    "name": "Gangadhar Shastri Gune Ayurved Mahavidyalaya",
    "city": "Ahmednagar",
    "est": "63 (9)",
    "seats": "\u20b965,000",
    "type": "",
    "filterType": "Private",
    "link": "maharashtra-ayush-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "AYUSH",
    "name": "Ayurved Mahavidyalaya, Panchavati",
    "city": "Nasik",
    "est": "75 (11)",
    "seats": "\u20b965,000",
    "type": "",
    "filterType": "Private",
    "link": "maharashtra-ayush-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "AYUSH",
    "name": "KVT Randhir Ayurved Mahavidyalaya",
    "city": "Boradi",
    "est": "75 (11)",
    "seats": "\u20b965,000",
    "type": "",
    "filterType": "Private",
    "link": "maharashtra-ayush-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "AYUSH",
    "name": "Shree Ayurved Mahavidyalaya",
    "city": "Nagpur",
    "est": "125 (19)",
    "seats": "\u20b965,000",
    "type": "",
    "filterType": "Private",
    "link": "maharashtra-ayush-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "AYUSH",
    "name": "Vidarbha Ayurved Mahavidyalaya",
    "city": "Amravati",
    "est": "63 (9)",
    "seats": "\u20b965,000",
    "type": "",
    "filterType": "Private",
    "link": "maharashtra-ayush-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "AYUSH",
    "name": "Radhakisan Toshniwal Ayurved Mahavidyalaya",
    "city": "Akola",
    "est": "75 (11)",
    "seats": "\u20b965,000",
    "type": "",
    "filterType": "Private",
    "link": "maharashtra-ayush-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "AYUSH",
    "name": "DMM Ayurved Mahavidyalaya",
    "city": "Yavatmal",
    "est": "75 (11)",
    "seats": "\u20b965,000",
    "type": "",
    "filterType": "Private",
    "link": "maharashtra-ayush-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "AYUSH",
    "name": "BSD Trust\u2019s Ayurvedic Mahavidyalaya",
    "city": "Vagholi, Pune",
    "est": "60 (9)",
    "seats": "\u20b92,40,000",
    "type": "",
    "filterType": "Private",
    "link": "maharashtra-ayush-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "AYUSH",
    "name": "PDEA\u2019s Ayurved Mahavidyalaya and Sanshodhan Kendra",
    "city": "Pune",
    "est": "60 (9)",
    "seats": "\u20b91,85,000",
    "type": "",
    "filterType": "Private",
    "link": "maharashtra-ayush-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "AYUSH",
    "name": "Sumatibhai Shah Ayurved Mahavidyalaya",
    "city": "Hadapsar, Pune",
    "est": "60 (9)",
    "seats": "\u20b91,81,000",
    "type": "",
    "filterType": "Private",
    "link": "maharashtra-ayush-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "AYUSH",
    "name": "Shri Vivekanand Nursing Home Trust\u2019s Ayurved Mahavidyalaya",
    "city": "Rahuri",
    "est": "60 (9)",
    "seats": "\u20b91,58,000",
    "type": "",
    "filterType": "Private",
    "link": "maharashtra-ayush-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "AYUSH",
    "name": "Pravara Medical Trust\u2019s Ayurved Mahavidyalaya & Eknath Ayurved Hosp",
    "city": "Shevgaon",
    "est": "100 (15)",
    "seats": "\u20b91,70,000",
    "type": "",
    "filterType": "Private",
    "link": "maharashtra-ayush-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "AYUSH",
    "name": "Siddhakala Ayurved Mahavidyalaya",
    "city": "Sangamner",
    "est": "60 (9)",
    "seats": "\u20b91,90,000",
    "type": "",
    "filterType": "Private",
    "link": "maharashtra-ayush-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "AYUSH",
    "name": "D.S. Naik Ayurved Mahavidyalaya",
    "city": "Nagaon",
    "est": "50 (8)",
    "seats": "\u20b92,34,000",
    "type": "",
    "filterType": "Private",
    "link": "maharashtra-ayush-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "AYUSH",
    "name": "K.C. Ajmera Ayurved Mahavidyalaya",
    "city": "Deopur, Dhule",
    "est": "60 (9)",
    "seats": "\u20b91,18,000",
    "type": "",
    "filterType": "Private",
    "link": "maharashtra-ayush-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "AYUSH",
    "name": "Chaitanya Ayurved Mahavidyalaya",
    "city": "Sakegaon",
    "est": "60 (9)",
    "seats": "\u20b92,34,000",
    "type": "",
    "filterType": "Private",
    "link": "maharashtra-ayush-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "AYUSH",
    "name": "Ashvin Rural Ayurved Mahavidyalaya",
    "city": "Ashvi Sangamner",
    "est": "100 (15)",
    "seats": "\u20b92,06,000",
    "type": "",
    "filterType": "Private",
    "link": "maharashtra-ayush-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "AYUSH",
    "name": "LRP Ayurved Mahavidyalaya",
    "city": "Islampur, Sangli",
    "est": "100 (15)",
    "seats": "\u20b91,98,000",
    "type": "",
    "filterType": "Private",
    "link": "maharashtra-ayush-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "AYUSH",
    "name": "Rural Institute Ayurved Research Centre",
    "city": "Khatau, Satara",
    "est": "50 (8)",
    "seats": "\u20b91,56,000",
    "type": "",
    "filterType": "Private",
    "link": "maharashtra-ayush-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "AYUSH",
    "name": "MES Ayurved Mahavidyalaya",
    "city": "Khed, Ratnagiri",
    "est": "60 (9)",
    "seats": "\u20b92,23,000",
    "type": "",
    "filterType": "Private",
    "link": "maharashtra-ayush-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "AYUSH",
    "name": "SMBT Ayurved Mahavidyalaya",
    "city": "Igatpuri, Nashik",
    "est": "100 (15)",
    "seats": "\u20b91,90,000",
    "type": "",
    "filterType": "Private",
    "link": "maharashtra-ayush-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "AYUSH",
    "name": "Matoshri Asarabai Darade Ayurved Mahavidyalaya",
    "city": "Yeola, Nashik",
    "est": "50 (8)",
    "seats": "\u20b91,40,000",
    "type": "",
    "filterType": "Private",
    "link": "maharashtra-ayush-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "AYUSH",
    "name": "Jai Shree Siddhivinayak Foundation\u2019s B. R. Harne Ayurved Mahavidyalaya",
    "city": "Thane",
    "est": "50 (8)",
    "seats": "\u20b91,75,000",
    "type": "",
    "filterType": "Private",
    "link": "maharashtra-ayush-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "AYUSH",
    "name": "Ramrao Patil Ayurved Mahavidyalaya",
    "city": "Purana, Parbhani",
    "est": "40 (6)",
    "seats": "\u20b91,03,000",
    "type": "",
    "filterType": "Private",
    "link": "maharashtra-ayush-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "AYUSH",
    "name": "Jai Shree Siddhivinayak Foundation\u2019s B. R. Harne Ayurved Mahavidyalaya",
    "city": "Thane",
    "est": "50 (8)",
    "seats": "\u20b91,75,000",
    "type": "",
    "filterType": "Private",
    "link": "maharashtra-ayush-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "AYUSH",
    "name": "Ramrao Patil Ayurved Mahavidyalaya",
    "city": "Purana, Parbhani",
    "est": "40 (6)",
    "seats": "\u20b91,03,000",
    "type": "",
    "filterType": "Private",
    "link": "maharashtra-ayush-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "AYUSH",
    "name": "Pandit Jawaharlal Nehru Institute of Homoeopathic Medical Sciences",
    "city": "Private",
    "est": "100 (15)",
    "seats": "\u20b919,000",
    "type": "",
    "filterType": "Private",
    "link": "maharashtra-ayush-counselling.html"
  },
  {
    "state": "Maharashtra",
    "course": "AYUSH",
    "name": "Indira Gandhi Memorial Hospital",
    "city": "Private",
    "est": "100 (15)",
    "seats": "\u20b940,000",
    "type": "",
    "filterType": "Private",
    "link": "maharashtra-ayush-counselling.html"
  },
  {
    "state": "Himachal Pradesh",
    "course": "MBBS",
    "name": "All India Institute of Medical Sciences",
    "city": "Bilaspur",
    "est": "2019",
    "seats": "100",
    "type": "Central Govt.",
    "filterType": "Govt",
    "link": "himachal-pradesh-mbbs-counselling.html"
  },
  {
    "state": "Kerala",
    "course": "AYUSH",
    "name": "Shree Narayan Institute of Ayurvedic Studies & Research",
    "city": "Kollam",
    "est": "2004",
    "seats": "100",
    "type": "\u20b95,25,000 - \u20b91,99,415",
    "filterType": "Private",
    "link": "kerala-ayush-counselling.html"
  },
  {
    "state": "Kerala",
    "course": "AYUSH",
    "name": "Ashtamgam Ayurveda Chikitsalayam & Vidyapeetham",
    "city": "Palakkad",
    "est": "2011",
    "seats": "-",
    "type": "\u20b92,68,050",
    "filterType": "Private",
    "link": "kerala-ayush-counselling.html"
  },
  {
    "state": "Kerala",
    "course": "AYUSH",
    "name": "Amrita School Of Ayurveda (Deemed University)",
    "city": "Amritapuri, Kollam",
    "est": "2004",
    "seats": "-",
    "type": "MCC AIQ",
    "filterType": "Private",
    "link": "kerala-ayush-counselling.html"
  },
  {
    "state": "Arunachal Pradesh",
    "course": "MBBS",
    "name": "Tomo Riba Institute of Health & Medical Sciences",
    "city": "Naharlagun",
    "est": "2018",
    "seats": "100",
    "type": "Central Govt.",
    "filterType": "Govt",
    "link": "arunachal-pradesh-mbbs-counselling.html"
  },
  {
    "state": "Mp",
    "course": "AYUSH",
    "name": "Mandsaur Institute of Ayurveda Education",
    "city": "Mandsaur",
    "est": "100",
    "seats": "-",
    "type": "",
    "filterType": "Private",
    "link": "mp-ayush-counselling.html"
  },
  {
    "state": "Mp",
    "course": "AYUSH",
    "name": "Shri Sai Institute of Ayurvedic Research and Medicine",
    "city": "Bhopal",
    "est": "100",
    "seats": "\u20b91,87,000",
    "type": "",
    "filterType": "Private",
    "link": "mp-ayush-counselling.html"
  },
  {
    "state": "Mp",
    "course": "AYUSH",
    "name": "Purnayu Ayurvedic Hospital and Research University",
    "city": "Jabalpur",
    "est": "100",
    "seats": "-",
    "type": "",
    "filterType": "Private",
    "link": "mp-ayush-counselling.html"
  },
  {
    "state": "Mp",
    "course": "AYUSH",
    "name": "Faculty of Ayurveda Mansarovar Global University",
    "city": "Sehore",
    "est": "100",
    "seats": "-",
    "type": "",
    "filterType": "Private",
    "link": "mp-ayush-counselling.html"
  },
  {
    "state": "Mp",
    "course": "AYUSH",
    "name": "Department of Ayurveda and Community, IES University",
    "city": "Bhopal",
    "est": "60",
    "seats": "-",
    "type": "",
    "filterType": "Private",
    "link": "mp-ayush-counselling.html"
  },
  {
    "state": "Mp",
    "course": "AYUSH",
    "name": "School of Ayurveda and Siddha Studies",
    "city": "Sehore",
    "est": "100",
    "seats": "-",
    "type": "",
    "filterType": "Private",
    "link": "mp-ayush-counselling.html"
  },
  {
    "state": "Andhra Pradesh",
    "course": "AYUSH",
    "name": "Maharaja Institute of Homoeopathic Medical Sciences",
    "city": "Vizianagaram",
    "est": "Private",
    "seats": "2007",
    "type": "100",
    "filterType": "Private",
    "link": "andhra-pradesh-ayush-counselling.html"
  },
  {
    "state": "Andhra Pradesh",
    "course": "AYUSH",
    "name": "Sri Adi Siva Sadguru Alli Saheb Sivaryula HMC",
    "city": "Thimmapuram, Guntakal",
    "est": "Private",
    "seats": "2017",
    "type": "100",
    "filterType": "Private",
    "link": "andhra-pradesh-ayush-counselling.html"
  },
  {
    "state": "Delhi",
    "course": "AYUSH",
    "name": "Ch. Brahm Prakash Ayurved Charak Sansthan",
    "city": "GGSIPU",
    "est": "2007",
    "seats": "100",
    "type": "\u20b91,06,700",
    "filterType": "Private",
    "link": "delhi-ayush-counselling.html"
  },
  {
    "state": "Manipur",
    "course": "MBBS",
    "name": "Regional Institute of Medical Sciences",
    "city": "Imphal",
    "est": "1972",
    "seats": "125",
    "type": "State Govt.",
    "filterType": "Govt",
    "link": "manipur-mbbs-counselling.html"
  },
  {
    "state": "Manipur",
    "course": "MBBS",
    "name": "Jawaharlal Nehru Institute of Medical Sciences",
    "city": "Porompet, Imphal",
    "est": "2010",
    "seats": "150",
    "type": "State Govt.",
    "filterType": "Govt",
    "link": "manipur-mbbs-counselling.html"
  },
  {
    "state": "Manipur",
    "course": "MBBS",
    "name": "Shija Academy of Health Sciences",
    "city": "Imphal",
    "est": "2021",
    "seats": "150",
    "type": "Private",
    "filterType": "Private",
    "link": "manipur-mbbs-counselling.html"
  },
  {
    "state": "Tamil Nadu",
    "course": "AYUSH",
    "name": "Akila Thiruvithamcore Siddha Vaidya Sangam",
    "city": "Thiruvithamcore",
    "est": "-",
    "seats": "40",
    "type": "",
    "filterType": "Private",
    "link": "tamil-nadu-ayush-counselling.html"
  },
  {
    "state": "Gujarat",
    "course": "MBBS",
    "name": "Surat Municipal Institute of Medical Education & Research (SMIMER)",
    "city": "Surat",
    "est": "1999",
    "seats": "250",
    "type": "State Govt.",
    "filterType": "Govt",
    "link": "gujarat-mbbs-counselling.html"
  },
  {
    "state": "Gujarat",
    "course": "MBBS",
    "name": "All India Institute of Medical Sciences (AIIMS)",
    "city": "Rajkot",
    "est": "2019",
    "seats": "75",
    "type": "Central Govt.",
    "filterType": "Govt",
    "link": "gujarat-mbbs-counselling.html"
  },
  {
    "state": "Gujarat",
    "course": "MBBS",
    "name": "Gujarat Adani Institute of Medical Sciences",
    "city": "Bhuj",
    "est": "2009",
    "seats": "150",
    "type": "Trust",
    "filterType": "Private",
    "link": "gujarat-mbbs-counselling.html"
  },
  {
    "state": "Gujarat",
    "course": "MBBS",
    "name": "Parul Institute of Medical Sciences & Research",
    "city": "Vadodara",
    "est": "2016",
    "seats": "200",
    "type": "Private",
    "filterType": "Private",
    "link": "gujarat-mbbs-counselling.html"
  },
  {
    "state": "Gujarat",
    "course": "MBBS",
    "name": "Dr. N D Desai Faculty of Medical Science and Research",
    "city": "Nadiad",
    "est": "2019",
    "seats": "150",
    "type": "Private",
    "filterType": "Private",
    "link": "gujarat-mbbs-counselling.html"
  },
  {
    "state": "Gujarat",
    "course": "MBBS",
    "name": "SAL Institute of Medical Sciences",
    "city": "Ahmedabad",
    "est": "2023",
    "seats": "150",
    "type": "Trust",
    "filterType": "Private",
    "link": "gujarat-mbbs-counselling.html"
  },
  {
    "state": "Gujarat",
    "course": "MBBS",
    "name": "Swaminarayan Institute of Medical Sciences & Research",
    "city": "Kalol",
    "est": "2023",
    "seats": "200",
    "type": "Trust",
    "filterType": "Private",
    "link": "gujarat-mbbs-counselling.html"
  },
  {
    "state": "Gujarat",
    "course": "MBBS",
    "name": "SBKS Medical Institute & Research Centre (Sumandeep Vidyapeeth)",
    "city": "Vadodara",
    "est": "2002",
    "seats": "250",
    "type": "Deemed",
    "filterType": "Deemed",
    "link": "gujarat-mbbs-counselling.html"
  },
  {
    "state": "Rajasthan",
    "course": "AYUSH",
    "name": "Post Graduate Institute of Ayurveda (PGIA), DSRRAU",
    "city": "Jodhpur",
    "est": "2003",
    "seats": "125",
    "type": "\u20b990,000",
    "filterType": "Private",
    "link": "rajasthan-ayush-counselling.html"
  },
  {
    "state": "Rajasthan",
    "course": "AYUSH",
    "name": "Government Ayurveda Mahavidhalaya",
    "city": "Jaipur",
    "est": "2021",
    "seats": "60",
    "type": "\u20b98,023",
    "filterType": "Private",
    "link": "rajasthan-ayush-counselling.html"
  },
  {
    "state": "Rajasthan",
    "course": "AYUSH",
    "name": "Government Ayurveda Mahavidhalaya",
    "city": "Kota",
    "est": "2021",
    "seats": "54",
    "type": "\u20b98,023",
    "filterType": "Private",
    "link": "rajasthan-ayush-counselling.html"
  },
  {
    "state": "Rajasthan",
    "course": "AYUSH",
    "name": "Government Ayurveda Mahavidhalaya",
    "city": "Bikaner",
    "est": "2021",
    "seats": "54",
    "type": "\u20b98,023",
    "filterType": "Private",
    "link": "rajasthan-ayush-counselling.html"
  },
  {
    "state": "Rajasthan",
    "course": "AYUSH",
    "name": "Government Ayurveda Mahavidhalaya",
    "city": "Bharatpur",
    "est": "2021",
    "seats": "51",
    "type": "\u20b98,023",
    "filterType": "Private",
    "link": "rajasthan-ayush-counselling.html"
  },
  {
    "state": "Rajasthan",
    "course": "AYUSH",
    "name": "Government Ayurveda Mahavidhalaya",
    "city": "Sikar",
    "est": "2021",
    "seats": "54",
    "type": "\u20b98,023",
    "filterType": "Private",
    "link": "rajasthan-ayush-counselling.html"
  },
  {
    "state": "Rajasthan",
    "course": "AYUSH",
    "name": "Government Ayurveda Mahavidhalaya",
    "city": "Kekeri, Ajmer",
    "est": "2021",
    "seats": "54",
    "type": "\u20b98,023",
    "filterType": "Private",
    "link": "rajasthan-ayush-counselling.html"
  },
  {
    "state": "Rajasthan",
    "course": "AYUSH",
    "name": "Shri Bhanwar Lal Duggar Ayurved Vishwabharati",
    "city": "Sardarsahar",
    "est": "2007",
    "seats": "60",
    "type": "\u20b92,00,000",
    "filterType": "Private",
    "link": "rajasthan-ayush-counselling.html"
  },
  {
    "state": "Rajasthan",
    "course": "AYUSH",
    "name": "Faculty of Ayurved, Jayoti Vidhyapeeth Women\u2019s University",
    "city": "Jaipur",
    "est": "2017",
    "seats": "60",
    "type": "\u20b94,50,000",
    "filterType": "Private",
    "link": "rajasthan-ayush-counselling.html"
  },
  {
    "state": "Rajasthan",
    "course": "AYUSH",
    "name": "Swasthya Kalyan Institute of Naturopathy & Yogic Sciences, Jaipur",
    "city": "Private",
    "est": "50",
    "seats": "\u20b990,000",
    "type": "",
    "filterType": "Private",
    "link": "rajasthan-ayush-counselling.html"
  },
  {
    "state": "Rajasthan",
    "course": "AYUSH",
    "name": "Shekhawati Institute of Naturopathy & Yogic Sciences, Sikar",
    "city": "Private",
    "est": "100",
    "seats": "\u20b990,000",
    "type": "",
    "filterType": "Private",
    "link": "rajasthan-ayush-counselling.html"
  },
  {
    "state": "Rajasthan",
    "course": "AYUSH",
    "name": "Shri Jagdishprasad Jhabarmal Tibrewala University, Jhunjhunu",
    "city": "Private",
    "est": "100",
    "seats": "\u20b950,000",
    "type": "",
    "filterType": "Private",
    "link": "rajasthan-ayush-counselling.html"
  },
  {
    "state": "West Bengal",
    "course": "AYUSH",
    "name": "Institute of Post Graduate Ayurvedic Education & Research",
    "city": "Kolkata",
    "est": "1976",
    "seats": "N/A",
    "type": "-",
    "filterType": "Private",
    "link": "west-bengal-ayush-counselling.html"
  },
  {
    "state": "West Bengal",
    "course": "AYUSH",
    "name": "Raghunath Ayurvedic Mahavidyalaya & Hospital",
    "city": "Medinipur",
    "est": "1949",
    "seats": "50",
    "type": "State: \u20b96,75,000 | Mgmt: \u20b99,75,000",
    "filterType": "Govt",
    "link": "west-bengal-ayush-counselling.html"
  },
  {
    "state": "West Bengal",
    "course": "AYUSH",
    "name": "National Institute of Homoeopathy (Central Inst.)",
    "city": "Kolkata",
    "est": "1975",
    "seats": "93",
    "type": "-",
    "filterType": "Private",
    "link": "west-bengal-ayush-counselling.html"
  },
  {
    "state": "Karnataka",
    "course": "AYUSH",
    "name": "Shri BM Kankanwadi Ayurved Mahavidyalaya",
    "city": "Belgaum",
    "est": "100",
    "seats": "\u20b94,95,000",
    "type": "",
    "filterType": "Private",
    "link": "karnataka-ayush-counselling.html"
  },
  {
    "state": "Karnataka",
    "course": "AYUSH",
    "name": "Indian Institute of Ayurvedic Medicine & Research",
    "city": "Bangalore",
    "est": "45",
    "seats": "\u20b91,50,000",
    "type": "",
    "filterType": "Private",
    "link": "karnataka-ayush-counselling.html"
  },
  {
    "state": "Karnataka",
    "course": "AYUSH",
    "name": "Hyderabad Karnataka Ed. Society\u2019s HMC",
    "city": "Gulbarga",
    "est": "100",
    "seats": "\u20b92,72,000",
    "type": "",
    "filterType": "Private",
    "link": "karnataka-ayush-counselling.html"
  },
  {
    "state": "Karnataka",
    "course": "AYUSH",
    "name": "Shree Shiv Basav Jyoti HMC",
    "city": "Belgaum",
    "est": "50",
    "seats": "\u20b91,25,000",
    "type": "",
    "filterType": "Private",
    "link": "karnataka-ayush-counselling.html"
  },
  {
    "state": "Karnataka",
    "course": "AYUSH",
    "name": "National Institute of Unani Medicine (Autonomous)",
    "city": "Bangalore",
    "est": "60",
    "seats": "\u20b925,000",
    "type": "",
    "filterType": "Private",
    "link": "karnataka-ayush-counselling.html"
  },
  {
    "state": "Up",
    "course": "AYUSH",
    "name": "Institute of Ayush Medical Sciences",
    "city": "Lucknow",
    "est": "100",
    "seats": "\u20b92,51,200",
    "type": "",
    "filterType": "Private",
    "link": "up-ayush-counselling.html"
  },
  {
    "state": "Up",
    "course": "AYUSH",
    "name": "Prakash Institute of Ayurvedic Medical Sciences",
    "city": "Bulandshahr",
    "est": "60",
    "seats": "\u20b92,60,500",
    "type": "",
    "filterType": "Private",
    "link": "up-ayush-counselling.html"
  },
  {
    "state": "Up",
    "course": "AYUSH",
    "name": "Dronacharya Ayurvedic Educational Institute",
    "city": "Saharanpur",
    "est": "60",
    "seats": "\u20b92,04,600",
    "type": "",
    "filterType": "Private",
    "link": "up-ayush-counselling.html"
  },
  {
    "state": "Up",
    "course": "AYUSH",
    "name": "Guru Gorakhnath Institute of Medical Sciences",
    "city": "Gorakhpur",
    "est": "100",
    "seats": "\u20b92,65,800",
    "type": "",
    "filterType": "Private",
    "link": "up-ayush-counselling.html"
  },
  {
    "state": "Up",
    "course": "AYUSH",
    "name": "Apex Institute of Ayurvedic Medicine",
    "city": "Mirzapur",
    "est": "100",
    "seats": "\u20b92,70,000",
    "type": "",
    "filterType": "Private",
    "link": "up-ayush-counselling.html"
  },
  {
    "state": "Up",
    "course": "AYUSH",
    "name": "Javitri Institute of Ayurvedic Medical Sciences",
    "city": "Lucknow",
    "est": "60",
    "seats": "\u20b92,04,600",
    "type": "",
    "filterType": "Private",
    "link": "up-ayush-counselling.html"
  },
  {
    "state": "Up",
    "course": "AYUSH",
    "name": "Chandrashekhar Singh Ayurvedic Sansthan",
    "city": "Kaushambi",
    "est": "60",
    "seats": "\u20b92,59,000",
    "type": "",
    "filterType": "Private",
    "link": "up-ayush-counselling.html"
  },
  {
    "state": "Up",
    "course": "AYUSH",
    "name": "Institute of Ayurveda, Major S.D. Singh University",
    "city": "Farrukhabad",
    "est": "100",
    "seats": "\u20b92,52,900",
    "type": "",
    "filterType": "Private",
    "link": "up-ayush-counselling.html"
  },
  {
    "state": "Up",
    "course": "AYUSH",
    "name": "RK Institute of Ayurvedic Medical Sciences",
    "city": "Bareilly",
    "est": "60",
    "seats": "\u20b92,04,600",
    "type": "",
    "filterType": "Private",
    "link": "up-ayush-counselling.html"
  },
  {
    "state": "Up",
    "course": "AYUSH",
    "name": "Rajshree Ayurvedic Medical and Hospital",
    "city": "Bareilly",
    "est": "60",
    "seats": "\u20b92,04,600",
    "type": "",
    "filterType": "Private",
    "link": "up-ayush-counselling.html"
  },
  {
    "state": "Up",
    "course": "AYUSH",
    "name": "Sardar Patel Institute of Ayurvedic Medical Sciences",
    "city": "Lucknow",
    "est": "100",
    "seats": "\u20b92,55,700",
    "type": "",
    "filterType": "Private",
    "link": "up-ayush-counselling.html"
  },
  {
    "state": "Up",
    "course": "AYUSH",
    "name": "Vaidya Yagyadutt Sharma Ayurved Mahavidyalaya",
    "city": "Bulandshahr",
    "est": "100",
    "seats": "\u20b92,59,100",
    "type": "",
    "filterType": "Private",
    "link": "up-ayush-counselling.html"
  },
  {
    "state": "Up",
    "course": "AYUSH",
    "name": "Jamia Tibbia",
    "city": "Deoband, Saharanpur",
    "est": "60",
    "seats": "\u20b91,50,000",
    "type": "",
    "filterType": "Private",
    "link": "up-ayush-counselling.html"
  },
  {
    "state": "Assam",
    "course": "MBBS",
    "name": "All India Institute of Medical Sciences",
    "city": "Guwahati",
    "est": "2020",
    "seats": "100",
    "type": "Central Govt.",
    "filterType": "Govt",
    "link": "assam-mbbs-counselling.html"
  },
  {
    "state": "Odisha",
    "course": "AYUSH",
    "name": "Gopabandhu Ayurveda Mahavidyalaya",
    "city": "Puri",
    "est": "Govt.",
    "seats": "63",
    "type": "",
    "filterType": "Private",
    "link": "odisha-ayush-counselling.html"
  },
  {
    "state": "Punjab",
    "course": "MBBS",
    "name": "All India Institute of Medical Sciences (AIIMS)",
    "city": "Bhatinda",
    "est": "2019",
    "seats": "100",
    "type": "Central Govt.",
    "filterType": "Govt",
    "link": "punjab-mbbs-counselling.html"
  },
  {
    "state": "Punjab",
    "course": "MBBS",
    "name": "Dr B R Ambedkar State Institute of Medical Sciences",
    "city": "Mohali",
    "est": "2021",
    "seats": "100",
    "type": "State Govt.",
    "filterType": "Govt",
    "link": "punjab-mbbs-counselling.html"
  },
  {
    "state": "Punjab",
    "course": "MBBS",
    "name": "Sri Guru Ram Das Institute of Medical Sciences (Sikh Minority)",
    "city": "Amritsar",
    "est": "1997",
    "seats": "150",
    "type": "Trust",
    "filterType": "Private",
    "link": "punjab-mbbs-counselling.html"
  },
  {
    "state": "Punjab",
    "course": "MBBS",
    "name": "Adesh Institute Of Medical Sciences & Research",
    "city": "Bhatinda",
    "est": "2006",
    "seats": "150",
    "type": "Trust",
    "filterType": "Private",
    "link": "punjab-mbbs-counselling.html"
  },
  {
    "state": "Punjab",
    "course": "MBBS",
    "name": "Punjab Institute of Medical Sciences",
    "city": "Jalandhar",
    "est": "2011",
    "seats": "150",
    "type": "Trust",
    "filterType": "Private",
    "link": "punjab-mbbs-counselling.html"
  },
  {
    "state": "Haryana",
    "course": "MBBS",
    "name": "Pt. B D Sharma Post Graduate Institute of Medical Sciences",
    "city": "Rohtak",
    "est": "1960",
    "seats": "250",
    "type": "State Govt.",
    "filterType": "Govt",
    "link": "haryana-mbbs-counselling.html"
  },
  {
    "state": "Haryana",
    "course": "MBBS",
    "name": "Pt Neki Ram Sharma GMC",
    "city": "Bhiwani",
    "est": "2025",
    "seats": "100",
    "type": "State Govt.",
    "filterType": "Govt",
    "link": "haryana-mbbs-counselling.html"
  },
  {
    "state": "Haryana",
    "course": "MBBS",
    "name": "Maharishi Markandeshwar Institute Of Medical Sciences & Research",
    "city": "Ambala",
    "est": "2003",
    "seats": "200",
    "type": "Deemed Uni.",
    "filterType": "Deemed",
    "link": "haryana-mbbs-counselling.html"
  },
  {
    "state": "Haryana",
    "course": "MBBS",
    "name": "Faculty of Medicine and Health Sciences (SGT University)",
    "city": "Gurgaon",
    "est": "2010",
    "seats": "150",
    "type": "Trust",
    "filterType": "Private",
    "link": "haryana-mbbs-counselling.html"
  },
  {
    "state": "Haryana",
    "course": "MBBS",
    "name": "Al Falah School Of Medical Sciences (Minority)",
    "city": "Faridabad",
    "est": "2019",
    "seats": "200",
    "type": "Private Uni.",
    "filterType": "Private",
    "link": "haryana-mbbs-counselling.html"
  },
  {
    "state": "Haryana",
    "course": "MBBS",
    "name": "Amrita School of Medicine",
    "city": "Faridabad",
    "est": "2023",
    "seats": "150",
    "type": "Deemed Uni.",
    "filterType": "Deemed",
    "link": "haryana-mbbs-counselling.html"
  },
  {
    "state": "Bihar",
    "course": "AYUSH",
    "name": "Swami Raghavendracharya Tridandi, Ayurved Mahavidyalaya",
    "city": "Gaya",
    "est": "60",
    "seats": "As per mgmt",
    "type": "",
    "filterType": "Private",
    "link": "bihar-ayush-counselling.html"
  },
  {
    "state": "Bihar",
    "course": "AYUSH",
    "name": "B.N.M. Homoeopathic Medical Hospital",
    "city": "Saharsa",
    "est": "50",
    "seats": "-",
    "type": "",
    "filterType": "Private",
    "link": "bihar-ayush-counselling.html"
  },
  {
    "state": "Chhattisgarh",
    "course": "MBBS",
    "name": "Chhattisgarh Institute of Medical Sciences",
    "city": "Bilaspur",
    "est": "2001",
    "seats": "150",
    "type": "State Govt.",
    "filterType": "Govt",
    "link": "chhattisgarh-mbbs-counselling.html"
  },
  {
    "state": "Chhattisgarh",
    "course": "MBBS",
    "name": "All India Institute of Medical Sciences",
    "city": "Raipur",
    "est": "2012",
    "seats": "125",
    "type": "Central Govt.",
    "filterType": "Govt",
    "link": "chhattisgarh-mbbs-counselling.html"
  },
  {
    "state": "Chhattisgarh",
    "course": "MBBS",
    "name": "Rajmata Srimati Devendra Kumari Singhdev GMC",
    "city": "Surguja",
    "est": "2016",
    "seats": "125",
    "type": "State Govt.",
    "filterType": "Govt",
    "link": "chhattisgarh-mbbs-counselling.html"
  },
  {
    "state": "Chhattisgarh",
    "course": "MBBS",
    "name": "Raipur Institute of Medical Sciences (RIMS)",
    "city": "Raipur",
    "est": "2016",
    "seats": "150",
    "type": "Society",
    "filterType": "Private",
    "link": "chhattisgarh-mbbs-counselling.html"
  },
  {
    "state": "Chhattisgarh",
    "course": "MBBS",
    "name": "Shri Shankaracharya Institute of Medical Sciences",
    "city": "Bhilai",
    "est": "2016",
    "seats": "250",
    "type": "Society",
    "filterType": "Private",
    "link": "chhattisgarh-mbbs-counselling.html"
  },
  {
    "state": "Chhattisgarh",
    "course": "MBBS",
    "name": "Shri Balaji Institute of Medical Science",
    "city": "Raipur",
    "est": "2021",
    "seats": "250",
    "type": "Society",
    "filterType": "Private",
    "link": "chhattisgarh-mbbs-counselling.html"
  },
  {
    "state": "Chhattisgarh",
    "course": "MBBS",
    "name": "Shri Rawatpura Sarkar Institute of Medical Sciences and Research",
    "city": "Nava Raipur",
    "est": "2024",
    "seats": "100",
    "type": "Trust",
    "filterType": "Private",
    "link": "chhattisgarh-mbbs-counselling.html"
  },
  {
    "state": "Haryana",
    "course": "AYUSH",
    "name": "MSM Institute of Ayurveda, BPSMV University",
    "city": "Khanpur Kalan, Sonipat",
    "est": "64",
    "seats": "\u20b967,500",
    "type": "",
    "filterType": "Private",
    "link": "haryana-ayush-counselling.html"
  },
  {
    "state": "Haryana",
    "course": "AYUSH",
    "name": "Faculty of Indian Medical System, SGT University",
    "city": "Gurugram",
    "est": "100",
    "seats": "\u20b94,77,500",
    "type": "",
    "filterType": "Private",
    "link": "haryana-ayush-counselling.html"
  },
  {
    "state": "Andhra Pradesh",
    "course": "MBBS",
    "name": "GMC, Rajiv Gandhi Institute of Medical Sciences",
    "city": "Kadapa",
    "est": "2006",
    "seats": "175",
    "type": "State Govt.",
    "filterType": "Govt",
    "link": "andhra-pradesh-mbbs-counselling.html"
  },
  {
    "state": "Andhra Pradesh",
    "course": "MBBS",
    "name": "Rajiv Gandhi Institute of Medical Sciences",
    "city": "Srikakulam",
    "est": "2008",
    "seats": "200",
    "type": "State Govt.",
    "filterType": "Govt",
    "link": "andhra-pradesh-mbbs-counselling.html"
  },
  {
    "state": "Andhra Pradesh",
    "course": "MBBS",
    "name": "GMC, Rajiv Gandhi Institute of Medical Sciences",
    "city": "Ongole",
    "est": "2011",
    "seats": "150",
    "type": "State Govt.",
    "filterType": "Govt",
    "link": "andhra-pradesh-mbbs-counselling.html"
  },
  {
    "state": "Andhra Pradesh",
    "course": "MBBS",
    "name": "All India Institute of Medical Sciences (AIIMS)",
    "city": "Mangalagiri",
    "est": "2018",
    "seats": "125",
    "type": "Central Govt.",
    "filterType": "Govt",
    "link": "andhra-pradesh-mbbs-counselling.html"
  },
  {
    "state": "Andhra Pradesh",
    "course": "MBBS",
    "name": "Alluri Sitaram Raju Academy of Medical Sciences",
    "city": "Eluru",
    "est": "2000",
    "seats": "250",
    "type": "Trust",
    "filterType": "Private",
    "link": "andhra-pradesh-mbbs-counselling.html"
  },
  {
    "state": "Andhra Pradesh",
    "course": "MBBS",
    "name": "P E S Institute of Medical Sciences and Research",
    "city": "Kuppam",
    "est": "2001",
    "seats": "150",
    "type": "Trust",
    "filterType": "Private",
    "link": "andhra-pradesh-mbbs-counselling.html"
  },
  {
    "state": "Andhra Pradesh",
    "course": "MBBS",
    "name": "Maharajah Institute of Medical Sciences",
    "city": "Vizianagaram",
    "est": "2002",
    "seats": "200",
    "type": "Trust",
    "filterType": "Private",
    "link": "andhra-pradesh-mbbs-counselling.html"
  },
  {
    "state": "Andhra Pradesh",
    "course": "MBBS",
    "name": "Konaseema Institute of Medical Sciences",
    "city": "Amalapuram",
    "est": "2005",
    "seats": "200",
    "type": "Trust",
    "filterType": "Private",
    "link": "andhra-pradesh-mbbs-counselling.html"
  },
  {
    "state": "Andhra Pradesh",
    "course": "MBBS",
    "name": "Fathima Instt. of Medical Sciences (Muslim Minority)",
    "city": "Kadapa",
    "est": "2010",
    "seats": "100",
    "type": "Trust",
    "filterType": "Private",
    "link": "andhra-pradesh-mbbs-counselling.html"
  },
  {
    "state": "Andhra Pradesh",
    "course": "MBBS",
    "name": "Great Eastern Medical School and Hospital",
    "city": "Srikakulam",
    "est": "2010",
    "seats": "150",
    "type": "Trust",
    "filterType": "Private",
    "link": "andhra-pradesh-mbbs-counselling.html"
  },
  {
    "state": "Andhra Pradesh",
    "course": "MBBS",
    "name": "NRI Institute of Medical Sciences",
    "city": "Vishakapatnam",
    "est": "2012",
    "seats": "250",
    "type": "Trust",
    "filterType": "Private",
    "link": "andhra-pradesh-mbbs-counselling.html"
  },
  {
    "state": "Andhra Pradesh",
    "course": "MBBS",
    "name": "Apollo Institute of Medical Sciences and Research",
    "city": "Chittoor",
    "est": "2016",
    "seats": "150",
    "type": "Society",
    "filterType": "Private",
    "link": "andhra-pradesh-mbbs-counselling.html"
  },
  {
    "state": "Andhra Pradesh",
    "course": "MBBS",
    "name": "Gayathri Vidya Parishad Institute of Health Care",
    "city": "Vishakapatnam",
    "est": "2016",
    "seats": "200",
    "type": "Society",
    "filterType": "Private",
    "link": "andhra-pradesh-mbbs-counselling.html"
  },
  {
    "state": "Andhra Pradesh",
    "course": "MBBS",
    "name": "Nimra Institute of Medical Sciences (Muslim Minority)",
    "city": "Vijayawada",
    "est": "2016",
    "seats": "200",
    "type": "Society",
    "filterType": "Private",
    "link": "andhra-pradesh-mbbs-counselling.html"
  },
  {
    "state": "Andhra Pradesh",
    "course": "MBBS",
    "name": "GITAM Institute of Medical Sciences and Research",
    "city": "Visakhapatnam",
    "est": "2015",
    "seats": "150",
    "type": "Deemed",
    "filterType": "Deemed",
    "link": "andhra-pradesh-mbbs-counselling.html"
  },
  {
    "state": "Kerala",
    "course": "MBBS",
    "name": "Amala Institute of Medical Sciences, Thrissur (Christian Minority)",
    "city": "2002",
    "est": "100",
    "seats": "Trust",
    "type": "",
    "filterType": "Private",
    "link": "kerala-mbbs-counselling.html"
  },
  {
    "state": "Kerala",
    "course": "MBBS",
    "name": "Pushpagiri Institute Of Medical Sciences and Research Centre (Christian Minority)",
    "city": "2002",
    "est": "100",
    "seats": "Trust",
    "type": "",
    "filterType": "Private",
    "link": "kerala-mbbs-counselling.html"
  },
  {
    "state": "Kerala",
    "course": "MBBS",
    "name": "Sree Uthradom Thiurnal Academy of Medical Sciences",
    "city": "2006",
    "est": "250",
    "seats": "Trust",
    "type": "",
    "filterType": "Private",
    "link": "kerala-mbbs-counselling.html"
  },
  {
    "state": "Kerala",
    "course": "MBBS",
    "name": "Azeezia Instt of Medical Science, Kollam (Muslim Minority)",
    "city": "2008",
    "est": "100",
    "seats": "Trust",
    "type": "",
    "filterType": "Private",
    "link": "kerala-mbbs-counselling.html"
  },
  {
    "state": "Kerala",
    "course": "MBBS",
    "name": "Sree Narayana Instt. of Medical Sciences, Ernakulam",
    "city": "2009",
    "est": "150",
    "seats": "Trust",
    "type": "",
    "filterType": "Private",
    "link": "kerala-mbbs-counselling.html"
  },
  {
    "state": "Kerala",
    "course": "MBBS",
    "name": "P K Das Institute of Medical Sciences, Palakkad",
    "city": "2014",
    "est": "250",
    "seats": "Trust",
    "type": "",
    "filterType": "Private",
    "link": "kerala-mbbs-counselling.html"
  },
  {
    "state": "Kerala",
    "course": "MBBS",
    "name": "Palakkad Institute of Medical Sciences, Palakkad",
    "city": "2024",
    "est": "100",
    "seats": "Trust",
    "type": "",
    "filterType": "Private",
    "link": "kerala-mbbs-counselling.html"
  },
  {
    "state": "Kerala",
    "course": "MBBS",
    "name": "Amrita School of Medicine",
    "city": "Kochi",
    "est": "2000",
    "seats": "150",
    "type": "Deemed",
    "filterType": "Deemed",
    "link": "kerala-mbbs-counselling.html"
  },
  {
    "state": "Meghalaya",
    "course": "MBBS",
    "name": "North Eastern Indira Gandhi Regional Institute of Health and Medical Sciences",
    "city": "Shillong",
    "est": "2008",
    "seats": "50",
    "type": "State Govt.",
    "filterType": "Govt",
    "link": "meghalaya-mbbs-counselling.html"
  },
  {
    "state": "Rajasthan",
    "course": "MBBS",
    "name": "All India Institute of Medical Sciences (Central Govt.)",
    "city": "2012",
    "est": "150",
    "seats": "AIIMS Norms",
    "type": "Jodhpur",
    "filterType": "Private",
    "link": "rajasthan-mbbs-counselling.html"
  },
  {
    "state": "Rajasthan",
    "course": "MBBS",
    "name": "American Int. Inst. of Medical Sciences (Private)",
    "city": "2016",
    "est": "150",
    "seats": "\u20b918,90,000",
    "type": "Udaipur",
    "filterType": "Private",
    "link": "rajasthan-mbbs-counselling.html"
  },
  {
    "state": "Rajasthan",
    "course": "MBBS",
    "name": "Ananta Institute of Medical Sciences & Research Centre (Society)",
    "city": "2016",
    "est": "150",
    "seats": "\u20b918,90,000",
    "type": "Rajsamand",
    "filterType": "Private",
    "link": "rajasthan-mbbs-counselling.html"
  },
  {
    "state": "Rajasthan",
    "course": "MBBS",
    "name": "Balvir Singh Tomar Institute of Medical Sciences (Private)",
    "city": "2025",
    "est": "150",
    "seats": "\u20b918,90,000",
    "type": "Jaipur",
    "filterType": "Private",
    "link": "rajasthan-mbbs-counselling.html"
  },
  {
    "state": "Rajasthan",
    "course": "MBBS",
    "name": "Geetanjali Institute of Medical Sciences (Private)",
    "city": "2025",
    "est": "150",
    "seats": "\u20b918,90,000",
    "type": "Jaipur",
    "filterType": "Private",
    "link": "rajasthan-mbbs-counselling.html"
  },
  {
    "state": "Rajasthan",
    "course": "MBBS",
    "name": "JNU Institute for Medical Sciences and Research Centre (Private)",
    "city": "2016",
    "est": "250",
    "seats": "\u20b923,00,000",
    "type": "Jaipur",
    "filterType": "Private",
    "link": "rajasthan-mbbs-counselling.html"
  },
  {
    "state": "Rajasthan",
    "course": "MBBS",
    "name": "National Institute of Medical Science & Research (Trust)",
    "city": "2004",
    "est": "250",
    "seats": "\u20b924,00,000",
    "type": "Jaipur",
    "filterType": "Private",
    "link": "rajasthan-mbbs-counselling.html"
  },
  {
    "state": "Rajasthan",
    "course": "MBBS",
    "name": "Pacific Institute of Medical Sciences (Society)",
    "city": "2015",
    "est": "250",
    "seats": "\u20b925,00,000",
    "type": "Udaipur",
    "filterType": "Private",
    "link": "rajasthan-mbbs-counselling.html"
  },
  {
    "state": "Rajasthan",
    "course": "MBBS",
    "name": "Pacific MC & Hospital (Trust)",
    "city": "2014",
    "est": "200",
    "seats": "\u20b925,00,000",
    "type": "Udaipur",
    "filterType": "Private",
    "link": "rajasthan-mbbs-counselling.html"
  },
  {
    "state": "West Bengal",
    "course": "MBBS",
    "name": "\u20b950,000",
    "city": "\u20b915,000",
    "est": "AC: \u20b91,20,000 | Non-AC: \u20b91,02,000",
    "seats": "\u20b92,28,000",
    "type": "\u20b99,00,000",
    "filterType": "Private",
    "link": "west-bengal-mbbs-counselling.html"
  },
  {
    "state": "West Bengal",
    "course": "MBBS",
    "name": "\u20b950,000",
    "city": "\u20b915,000",
    "est": "\u20b960,000 (Mess extra)",
    "seats": "\u20b92,50,000",
    "type": "\u20b99,50,000",
    "filterType": "Private",
    "link": "west-bengal-mbbs-counselling.html"
  },
  {
    "state": "West Bengal",
    "course": "MBBS",
    "name": "\u20b950,000",
    "city": "\u20b915,000",
    "est": "AC: \u20b996,000 | Non-AC: \u20b966,000 | Mess: \u20b972,000 yearly",
    "seats": "\u20b92,74,000",
    "type": "\u20b910,94,000",
    "filterType": "Private",
    "link": "west-bengal-mbbs-counselling.html"
  },
  {
    "state": "West Bengal",
    "course": "MBBS",
    "name": "\u20b950,000",
    "city": "\u20b915,000",
    "est": "AC: \u20b91,68,000 yearly | Non-AC: \u20b91,44,000 yearly",
    "seats": "\u20b92,74,000",
    "type": "\u20b910,94,000",
    "filterType": "Private",
    "link": "west-bengal-mbbs-counselling.html"
  },
  {
    "state": "West Bengal",
    "course": "MBBS",
    "name": "\u20b950,000",
    "city": "\u20b915,000",
    "est": "To be notified",
    "seats": "\u20b92,74,000",
    "type": "\u20b910,85,000",
    "filterType": "Private",
    "link": "west-bengal-mbbs-counselling.html"
  },
  {
    "state": "West Bengal",
    "course": "MBBS",
    "name": "\u20b950,000",
    "city": "\u20b915,000",
    "est": "To be notified",
    "seats": "\u20b92,50,000",
    "type": "\u20b99,50,000",
    "filterType": "Private",
    "link": "west-bengal-mbbs-counselling.html"
  },
  {
    "state": "West Bengal",
    "course": "MBBS",
    "name": "\u20b950,000",
    "city": "\u20b915,000",
    "est": "\u20b94,500 monthly",
    "seats": "\u20b92,00,000",
    "type": "\u20b98,00,000",
    "filterType": "Private",
    "link": "west-bengal-mbbs-counselling.html"
  },
  {
    "state": "West Bengal",
    "course": "MBBS",
    "name": "\u20b950,000",
    "city": "\u20b915,000",
    "est": "AC: \u20b92,31,600 yearly | Non-AC: \u20b91,58,400 yearly",
    "seats": "\u20b92,50,000",
    "type": "\u20b99,50,000",
    "filterType": "Private",
    "link": "west-bengal-mbbs-counselling.html"
  },
  {
    "state": "West Bengal",
    "course": "MBBS",
    "name": "\u20b950,000",
    "city": "\u20b915,000",
    "est": "AC: \u20b92,72,000 yearly | Non-AC: \u20b91,74,000 yearly",
    "seats": "\u20b92,74,000",
    "type": "\u20b910,94,000",
    "filterType": "Private",
    "link": "west-bengal-mbbs-counselling.html"
  },
  {
    "state": "West Bengal",
    "course": "MBBS",
    "name": "\u20b950,000",
    "city": "\u20b925,000",
    "est": "To be notified",
    "seats": "\u20b94,00,000",
    "type": "\u20b910,00,000",
    "filterType": "Private",
    "link": "west-bengal-mbbs-counselling.html"
  },
  {
    "state": "West Bengal",
    "course": "MBBS",
    "name": "To be notified",
    "city": "To be notified",
    "est": "To be notified",
    "seats": "To be notified",
    "type": "To be notified",
    "filterType": "Private",
    "link": "west-bengal-mbbs-counselling.html"
  },
  {
    "state": "West Bengal",
    "course": "MBBS",
    "name": "To be notified",
    "city": "To be notified",
    "est": "To be notified",
    "seats": "To be notified",
    "type": "To be notified",
    "filterType": "Private",
    "link": "west-bengal-mbbs-counselling.html"
  },
  {
    "state": "West Bengal",
    "course": "MBBS",
    "name": "To be notified",
    "city": "To be notified",
    "est": "To be notified",
    "seats": "To be notified",
    "type": "To be notified",
    "filterType": "Private",
    "link": "west-bengal-mbbs-counselling.html"
  },
  {
    "state": "West Bengal",
    "course": "MBBS",
    "name": "To be notified",
    "city": "To be notified",
    "est": "To be notified",
    "seats": "To be notified",
    "type": "To be notified",
    "filterType": "Private",
    "link": "west-bengal-mbbs-counselling.html"
  },
  {
    "state": "West Bengal",
    "course": "MBBS",
    "name": "Institute of Postgraduate Medical Education & Research, Kolkata",
    "city": "WBUHS, Kolkata",
    "est": "State Govt.",
    "seats": "1957",
    "type": "200",
    "filterType": "Private",
    "link": "west-bengal-mbbs-counselling.html"
  },
  {
    "state": "West Bengal",
    "course": "MBBS",
    "name": "AIIMS, Kalyani, Nadia",
    "city": "AIIMS (New Delhi)",
    "est": "Central Govt.",
    "seats": "2019",
    "type": "125",
    "filterType": "Govt",
    "link": "west-bengal-mbbs-counselling.html"
  },
  {
    "state": "West Bengal",
    "course": "MBBS",
    "name": "ICARE Institute of Medical Sciences & Research, Haldia",
    "city": "WBUHS, Kolkata",
    "est": "Trust",
    "seats": "2011",
    "type": "150",
    "filterType": "Private",
    "link": "west-bengal-mbbs-counselling.html"
  },
  {
    "state": "West Bengal",
    "course": "MBBS",
    "name": "Gouri Devi Institute of Medical Sciences and Hospital, Durgapur",
    "city": "WBUHS, Kolkata",
    "est": "Society",
    "seats": "2016",
    "type": "200",
    "filterType": "Private",
    "link": "west-bengal-mbbs-counselling.html"
  },
  {
    "state": "West Bengal",
    "course": "MBBS",
    "name": "Jagannath Gupta Institute of Medical Sciences & Hospital, Kolkata",
    "city": "WBUHS, Kolkata",
    "est": "Trust",
    "seats": "2018",
    "type": "200",
    "filterType": "Private",
    "link": "west-bengal-mbbs-counselling.html"
  },
  {
    "state": "West Bengal",
    "course": "MBBS",
    "name": "Shri Ramkrishna Institute of Medical Sciences & Sanaka Hospitals, Durgapur",
    "city": "WBUHS, Kolkata",
    "est": "Trust",
    "seats": "2019",
    "type": "250",
    "filterType": "Private",
    "link": "west-bengal-mbbs-counselling.html"
  },
  {
    "state": "West Bengal",
    "course": "MBBS",
    "name": "JIS School of Medical Science & Research, Howrah",
    "city": "JIS University, Kolkata",
    "est": "Trust",
    "seats": "2023",
    "type": "150",
    "filterType": "Private",
    "link": "west-bengal-mbbs-counselling.html"
  },
  {
    "state": "West Bengal",
    "course": "MBBS",
    "name": "East West Institute of Medical Sciences and Research, Purba Bardhaman",
    "city": "WBUHS",
    "est": "Private",
    "seats": "2024",
    "type": "50",
    "filterType": "Private",
    "link": "west-bengal-mbbs-counselling.html"
  },
  {
    "state": "West Bengal",
    "course": "MBBS",
    "name": "Krishnanagar Institute of Medical Sciences, Nadia",
    "city": "WBUHS",
    "est": "Private",
    "seats": "2024",
    "type": "100",
    "filterType": "Private",
    "link": "west-bengal-mbbs-counselling.html"
  },
  {
    "state": "West Bengal",
    "course": "MBBS",
    "name": "Raniganj Institute of Medical Sciences, Paschim Bardhaman",
    "city": "WBUHS",
    "est": "Private",
    "seats": "2025",
    "type": "100",
    "filterType": "Private",
    "link": "west-bengal-mbbs-counselling.html"
  },
  {
    "state": "Mp",
    "course": "MBBS",
    "name": "All India Institute of Medical Sciences (AIIMS)",
    "city": "Bhopal",
    "est": "2012",
    "seats": "125",
    "type": "AIIMS Norms",
    "filterType": "Govt",
    "link": "mp-mbbs-counselling.html"
  },
  {
    "state": "Mp",
    "course": "MBBS",
    "name": "Chhindwara Institute of Medical Sciences (CIMS) (State Govt.)",
    "city": "Chhindwara",
    "est": "2019",
    "seats": "150",
    "type": "\u20b91,14,000",
    "filterType": "Private",
    "link": "mp-mbbs-counselling.html"
  },
  {
    "state": "Mp",
    "course": "MBBS",
    "name": "Sri Aurobindo Institute of Medical Sciences (SAIMS)",
    "city": "Indore",
    "est": "2003",
    "seats": "250",
    "type": "\u20b99,53,000",
    "filterType": "Private",
    "link": "mp-mbbs-counselling.html"
  },
  {
    "state": "Mp",
    "course": "MBBS",
    "name": "Amaltas Institute of Medical Sciences",
    "city": "Dewas",
    "est": "2016",
    "seats": "250",
    "type": "\u20b99,53,000",
    "filterType": "Private",
    "link": "mp-mbbs-counselling.html"
  },
  {
    "state": "Mp",
    "course": "MBBS",
    "name": "Mahaveer Institute of Medical Sciences & Research",
    "city": "Bhopal",
    "est": "2020",
    "seats": "150",
    "type": "~\u20b98.40 Lakh",
    "filterType": "Private",
    "link": "mp-mbbs-counselling.html"
  },
  {
    "state": "Mp",
    "course": "MBBS",
    "name": "Sri Satya Sai University of Technology & Medical Sci.",
    "city": "Sehore",
    "est": "2024",
    "seats": "100",
    "type": "~\u20b911.00 Lakh",
    "filterType": "Private",
    "link": "mp-mbbs-counselling.html"
  },
  {
    "state": "Delhi",
    "course": "MBBS",
    "name": "All India Institute of Medical Sciences",
    "city": "AIIMS (Autonomous)",
    "est": "1956",
    "seats": "132",
    "type": "Central Govt.",
    "filterType": "Govt",
    "link": "delhi-mbbs-counselling.html"
  },
  {
    "state": "Delhi",
    "course": "MBBS",
    "name": "Atal Bihari Vajpayee Institute of Medical Sciences (RML)",
    "city": "GGSIPU",
    "est": "2008",
    "seats": "100",
    "type": "Central Govt.",
    "filterType": "Govt",
    "link": "delhi-mbbs-counselling.html"
  },
  {
    "state": "Delhi",
    "course": "MBBS",
    "name": "Hamdard Institute of Medical Sciences & Research (HIMSR)",
    "city": "Jamia Hamdard",
    "est": "2012",
    "seats": "150",
    "type": "Deemed Univ.",
    "filterType": "Deemed",
    "link": "delhi-mbbs-counselling.html"
  },
  {
    "state": "Telangana",
    "course": "MBBS",
    "name": "Rajiv Gandhi Institute of Medical Sciences, Adilabad",
    "city": "2008",
    "est": "100",
    "seats": "State Govt.",
    "type": "",
    "filterType": "Private",
    "link": "telangana-mbbs-counselling.html"
  },
  {
    "state": "Telangana",
    "course": "MBBS",
    "name": "Kamineni Institute of Medical Sciences, Narketpally",
    "city": "1999",
    "est": "200",
    "seats": "Private",
    "type": "",
    "filterType": "Private",
    "link": "telangana-mbbs-counselling.html"
  },
  {
    "state": "Telangana",
    "course": "MBBS",
    "name": "Mediciti Institute of Medical Sciences, Ghanpur, Hyderabad",
    "city": "2001",
    "est": "150",
    "seats": "Private",
    "type": "",
    "filterType": "Private",
    "link": "telangana-mbbs-counselling.html"
  },
  {
    "state": "Telangana",
    "course": "MBBS",
    "name": "Prathima Institute of Medical Sciences, Karimnagar",
    "city": "2001",
    "est": "200",
    "seats": "Private",
    "type": "",
    "filterType": "Private",
    "link": "telangana-mbbs-counselling.html"
  },
  {
    "state": "Telangana",
    "course": "MBBS",
    "name": "Chalmeda Anand Rao Institute of Medical Science, Karimnagar",
    "city": "2003",
    "est": "150",
    "seats": "Private",
    "type": "",
    "filterType": "Private",
    "link": "telangana-mbbs-counselling.html"
  },
  {
    "state": "Telangana",
    "course": "MBBS",
    "name": "Apollo Institute of Medical Sciences and Research, Hyderabad",
    "city": "2012",
    "est": "100",
    "seats": "Private",
    "type": "",
    "filterType": "Private",
    "link": "telangana-mbbs-counselling.html"
  },
  {
    "state": "Telangana",
    "course": "MBBS",
    "name": "Malla Reddy Institute of Medical Sciences, Hyderabad",
    "city": "2012",
    "est": "150",
    "seats": "Private",
    "type": "",
    "filterType": "Private",
    "link": "telangana-mbbs-counselling.html"
  },
  {
    "state": "Telangana",
    "course": "MBBS",
    "name": "Kamineni Academy of Medical Sciences & Research Centre, Hyderabad",
    "city": "2013",
    "est": "150",
    "seats": "Private",
    "type": "",
    "filterType": "Private",
    "link": "telangana-mbbs-counselling.html"
  },
  {
    "state": "Telangana",
    "course": "MBBS",
    "name": "Mahavir Institute Of Medical Sciences, Vikarabad, Telengana",
    "city": "2016",
    "est": "150",
    "seats": "Private",
    "type": "",
    "filterType": "Private",
    "link": "telangana-mbbs-counselling.html"
  },
  {
    "state": "Telangana",
    "course": "MBBS",
    "name": "RVM Institute of Medical sciences and Research Centre, Medak",
    "city": "2016",
    "est": "150",
    "seats": "Private",
    "type": "",
    "filterType": "Private",
    "link": "telangana-mbbs-counselling.html"
  },
  {
    "state": "Telangana",
    "course": "MBBS",
    "name": "Dr. Patnam Mahender Reddy Institute of Medical Sciences, Chevella",
    "city": "2019",
    "est": "150",
    "seats": "Private",
    "type": "",
    "filterType": "Private",
    "link": "telangana-mbbs-counselling.html"
  },
  {
    "state": "Telangana",
    "course": "MBBS",
    "name": "Mamata Academy of Medical Sciences, Bachupally",
    "city": "2019",
    "est": "150",
    "seats": "Private",
    "type": "",
    "filterType": "Private",
    "link": "telangana-mbbs-counselling.html"
  },
  {
    "state": "Telangana",
    "course": "MBBS",
    "name": "Surabhi Institute of Medical Sciences, Siddipet",
    "city": "2019",
    "est": "150",
    "seats": "Private",
    "type": "",
    "filterType": "Private",
    "link": "telangana-mbbs-counselling.html"
  },
  {
    "state": "Telangana",
    "course": "MBBS",
    "name": "Shadan Institute of Medical Sciences, Peerancheru, Hyderabad",
    "city": "2005",
    "est": "150",
    "seats": "Minority",
    "type": "",
    "filterType": "Private",
    "link": "telangana-mbbs-counselling.html"
  },
  {
    "state": "Telangana",
    "course": "MBBS",
    "name": "Ayyan Institute of Medical Sciences, Rangareddy",
    "city": "2018",
    "est": "150",
    "seats": "Minority",
    "type": "",
    "filterType": "Private",
    "link": "telangana-mbbs-counselling.html"
  },
  {
    "state": "Pondicherry",
    "course": "MBBS",
    "name": "Jawaharlal Institute of Postgraduate Medical Education & Research (JIPMER)",
    "city": "Autonomous",
    "est": "1956",
    "seats": "243",
    "type": "Central Govt.",
    "filterType": "Govt",
    "link": "pondicherry-mbbs-counselling.html"
  },
  {
    "state": "Pondicherry",
    "course": "MBBS",
    "name": "Pondicherry Institute of Medical Sciences & Research (Christian Min.)",
    "city": "Pondicherry Uni.",
    "est": "2000",
    "seats": "150",
    "type": "Trust",
    "filterType": "Private",
    "link": "pondicherry-mbbs-counselling.html"
  },
  {
    "state": "Pondicherry",
    "course": "MBBS",
    "name": "Sri Lakshmi Narayana Institute of Medical Sciences",
    "city": "Bharath Institute",
    "est": "2006",
    "seats": "250",
    "type": "Deemed",
    "filterType": "Deemed",
    "link": "pondicherry-mbbs-counselling.html"
  },
  {
    "state": "Gujarat",
    "course": "AYUSH",
    "name": "State Model Institute of Ayurveda Sciences",
    "city": "Gandhinagar",
    "est": "2015",
    "seats": "75",
    "type": "\u20b96,000",
    "filterType": "Private",
    "link": "gujarat-ayush-counselling.html"
  },
  {
    "state": "Gujarat",
    "course": "AYUSH",
    "name": "Shree Gulab Kunverba Ayurveda Mahavidyalaya",
    "city": "Jamnagar",
    "est": "1946",
    "seats": "50",
    "type": "\u20b95,429",
    "filterType": "Private",
    "link": "gujarat-ayush-counselling.html"
  },
  {
    "state": "Gujarat",
    "course": "AYUSH",
    "name": "Institute for Post Graduate Teaching & Research",
    "city": "Jamnagar",
    "est": "1956",
    "seats": "125",
    "type": "\u20b94,98,588",
    "filterType": "Private",
    "link": "gujarat-ayush-counselling.html"
  },
  {
    "state": "Gujarat",
    "course": "AYUSH",
    "name": "J.S. Ayurved Mahavidyalaya",
    "city": "Nadiad",
    "est": "1938",
    "seats": "100",
    "type": "\u20b92,67,000",
    "filterType": "Private",
    "link": "gujarat-ayush-counselling.html"
  },
  {
    "state": "Gujarat",
    "course": "AYUSH",
    "name": "Shri Balahanuman Ayurved Mahavidyalaya",
    "city": "Gandhinagar",
    "est": "1963",
    "seats": "35",
    "type": "\u20b92,71,000",
    "filterType": "Private",
    "link": "gujarat-ayush-counselling.html"
  },
  {
    "state": "Gujarat",
    "course": "AYUSH",
    "name": "Parul Institute of Ayurved",
    "city": "Vadodara",
    "est": "2006",
    "seats": "100",
    "type": "\u20b93,75,000",
    "filterType": "Private",
    "link": "gujarat-ayush-counselling.html"
  },
  {
    "state": "Gujarat",
    "course": "AYUSH",
    "name": "Manjushree Research Institute of Ayurvedic Science",
    "city": "Gandhinagar",
    "est": "2006",
    "seats": "100",
    "type": "\u20b93,15,000",
    "filterType": "Private",
    "link": "gujarat-ayush-counselling.html"
  },
  {
    "state": "Gujarat",
    "course": "AYUSH",
    "name": "Shri V.M. Mehta Institute of Ayurved",
    "city": "Rajkot",
    "est": "2014",
    "seats": "60",
    "type": "\u20b92,71,000",
    "filterType": "Private",
    "link": "gujarat-ayush-counselling.html"
  },
  {
    "state": "Gujarat",
    "course": "AYUSH",
    "name": "Global Institute of Ayurveda",
    "city": "Rajkot",
    "est": "2014",
    "seats": "60",
    "type": "\u20b92,71,000",
    "filterType": "Private",
    "link": "gujarat-ayush-counselling.html"
  },
  {
    "state": "Gujarat",
    "course": "AYUSH",
    "name": "K.J. Institute of Ayurveda & Research",
    "city": "Vadodara",
    "est": "2015",
    "seats": "60",
    "type": "\u20b92,71,000",
    "filterType": "Private",
    "link": "gujarat-ayush-counselling.html"
  },
  {
    "state": "Gujarat",
    "course": "AYUSH",
    "name": "Indian Institute of Ayurved Research & Hospital",
    "city": "Rajkot",
    "est": "2016",
    "seats": "100",
    "type": "\u20b92,91,000",
    "filterType": "Private",
    "link": "gujarat-ayush-counselling.html"
  },
  {
    "state": "Gujarat",
    "course": "AYUSH",
    "name": "Parul Institute of Homoeopathy & Research",
    "city": "Vadodara",
    "est": "2007",
    "seats": "100",
    "type": "\u20b980,000",
    "filterType": "Private",
    "link": "gujarat-ayush-counselling.html"
  },
  {
    "state": "Gujarat",
    "course": "AYUSH",
    "name": "Laxmiben Homoeopathy Institute & Research Centre",
    "city": "Mehsana",
    "est": "2017",
    "seats": "100",
    "type": "\u20b984,000",
    "filterType": "Private",
    "link": "gujarat-ayush-counselling.html"
  }
];
